const Map<String, String> stringsFa = {
  'Home': 'خانه',
  'Servers': 'سرورها',
  'Routing': 'مسیریابی',
  'Settings': 'تنظیمات',
  'About': 'درباره',
  'Disconnected': 'قطع شده',
  'Tap to connect': 'برای اتصال بزنید',
  'Connecting': 'در حال اتصال',
  'Connecting…': 'در حال اتصال…',
  'Starting the tunnel': 'در حال راه‌اندازی تونل',
  'Connected': 'متصل',
  'Connect': 'اتصال',
  'Disconnect': 'قطع اتصال',
  'Quit': 'خروج',
  'Show {}': 'نمایش {}',
  '{} is connected': '{} متصل است',
  '{} is disconnected': '{} قطع شد',
  'Your traffic is routed through the proxy.': 'ترافیک شما از طریق پروکسی عبور می‌کند.',
  'Your traffic is going directly.': 'ترافیک شما مستقیم می‌رود.',
  'Proxy': 'پروکسی',
  'TUN': 'TUN',
  'Down': 'دانلود',
  'Up': 'آپلود',
  'Ping': 'پینگ',
  'Mixed': 'ترکیبی',
  'Copy address': 'کپی نشانی',
  'Copied {}': '{} کپی شد',
  'Test latency': 'آزمایش تأخیر',
  'Free configs': 'کانفیگ‌های رایگان',
  'Share all servers': 'اشتراک‌گذاری همه سرورها',
  'Add server': 'افزودن سرور',
  'Sort servers': 'مرتب‌سازی سرورها',
  'Oldest first': 'قدیمی‌ترین',
  'Newest first': 'جدیدترین',
  'Lowest ping': 'کمترین پینگ',
  'Name': 'نام',
  'Protocol': 'پروتکل',
  'No servers yet. Tap + to add one.': 'هنوز سروری نیست. برای افزودن + را بزنید.',
  'Delete server?': 'سرور حذف شود؟',
  'Cancel': 'لغو',
  'Delete': 'حذف',
  'Clipboard is empty': 'کلیپ‌بورد خالی است',
  'No share links found in the clipboard': 'لینک اشتراکی در کلیپ‌بورد پیدا نشد',
  'Added 1 server': '۱ سرور اضافه شد',
  'Added {} servers': '{} سرور اضافه شد',
  'Added {} server(s), {} line(s) had errors': '{} سرور اضافه شد، {} خط خطا داشت',
  'No servers found': 'سروری پیدا نشد',
  'Password': 'گذرواژه',
  'File password': 'گذرواژه فایل',
  'Open': 'باز کردن',
  'Subscription URL': 'نشانی اشتراک',
  'Import': 'وارد کردن',
  'Paste from clipboard': 'چسباندن از کلیپ‌بورد',
  'One or more vless, vmess, trojan or ss links': 'یک یا چند لینک vless، vmess، trojan یا ss',
  'Download a whole list of servers': 'دانلود یک فهرست کامل از سرورها',
  'Import .pray file': 'وارد کردن فایل .pray',
  'Servers shared by another Pray app': 'سرورهای به اشتراک گذاشته‌شده از برنامه‌ی Pray دیگر',
  'Scan QR code': 'اسکن کد QR',
  'Use the camera': 'استفاده از دوربین',
  'QR scanning': 'اسکن QR',
  '{} arrives with the Xray core.': '{} همراه با هسته‌ی Xray می‌رسد.',
  'Enter a valid address and port (1-65535).': 'یک نشانی و پورت معتبر وارد کنید (۱ تا ۶۵۵۳۵).',
  'Edit server': 'ویرایش سرور',
  'Address': 'نشانی',
  'Port': 'پورت',
  'UUID': 'UUID',
  'Save': 'ذخیره',
  'Add': 'افزودن',
  'Remove': 'حذف',
  'Done': 'انجام شد',
  'Close': 'بستن',
  'Copy': 'کپی',
  'Link': 'لینک',
  'File': 'فایل',
  'Search': 'جستجو',
  'More': 'بیشتر',
  'Share': 'اشتراک‌گذاری',
  'Edit': 'ویرایش',
  'Pin to top': 'سنجاق به بالا',
  'Unpin': 'برداشتن سنجاق',
  'Enter a password or turn protection off.': 'گذرواژه وارد کنید یا محافظت را خاموش کنید.',
  'Saved {}': '{} ذخیره شد',
  'Save {}': 'ذخیره {}',
  'Link copied': 'لینک کپی شد',
  'Links copied': 'لینک‌ها کپی شد',
  'Protect with a password': 'محافظت با گذرواژه',
  'Only people with the password can open it': 'فقط کسانی که گذرواژه دارند می‌توانند آن را باز کنند',
  'Any Pray app can open it': 'هر برنامه‌ی Pray می‌تواند آن را باز کند',
  'Too long for a QR code': 'برای کد QR بیش از حد طولانی است',
  'Where traffic goes': 'مقصد ترافیک',
  'Proxy everything': 'همه چیز از پروکسی',
  'Bypass local network': 'عبور مستقیم شبکه‌ی محلی',
  'Bypass Iran': 'عبور مستقیم ایران',
  'All traffic goes through the server': 'همه‌ی ترافیک از سرور عبور می‌کند',
  'Local addresses connect directly': 'نشانی‌های محلی مستقیم متصل می‌شوند',
  'Iranian sites and IPs connect directly': 'سایت‌ها و IPهای ایرانی مستقیم متصل می‌شوند',
  ' — disconnect to change': ' — برای تغییر قطع کنید',
  'Proxy everything: all traffic goes through the server.': 'همه چیز از پروکسی: همه‌ی ترافیک از سرور عبور می‌کند.',
  'Bypass local network: only addresses on your own network (router, printers, other devices) connect directly. Everything else goes through the server.': 'عبور مستقیم شبکه‌ی محلی: فقط نشانی‌های شبکه‌ی خودتان (مودم، چاپگر، دستگاه‌های دیگر) مستقیم متصل می‌شوند. بقیه از سرور عبور می‌کنند.',
  'Bypass Iran: Iranian sites (.ir and known Iranian domains) and Iranian IP addresses connect directly, as well as your local network. Everything else goes through the server.': 'عبور مستقیم ایران: سایت‌های ایرانی (دامنه‌های ir. و دامنه‌های شناخته‌شده‌ی ایرانی) و نشانی‌های IP ایران و همچنین شبکه‌ی محلی مستقیم متصل می‌شوند. بقیه از سرور عبور می‌کنند.',
  'Ad blocking': 'مسدودسازی تبلیغات',
  'Off': 'خاموش',
  'Standard': 'استاندارد',
  'Strict': 'سخت‌گیرانه',
  'How it works: while connected, Pray looks at the name of every site or server an app tries to reach and drops the connection if the name is on a block list. Nothing is installed on your device and no traffic is read.': 'طرز کار: هنگام اتصال، Pray نام هر سایت یا سروری را که یک برنامه می‌خواهد به آن برسد بررسی می‌کند و اگر نام در فهرست مسدودی باشد، اتصال را قطع می‌کند. چیزی روی دستگاه شما نصب نمی‌شود و ترافیک خوانده نمی‌شود.',
  'Off: nothing is blocked.': 'خاموش: هیچ چیز مسدود نمی‌شود.',
  'Standard: blocks the well-known ad networks and trackers from the built-in geo data.': 'استاندارد: شبکه‌های تبلیغاتی و ردیاب‌های شناخته‌شده را از داده‌ی جغرافیایی داخلی مسدود می‌کند.',
  'Strict: Standard plus extra ad, tracker and analytics domains built into Pray, including Iranian ad networks. A few apps may stop working.': 'سخت‌گیرانه: استاندارد به‌علاوه‌ی دامنه‌های تبلیغاتی، ردیاب و تحلیلی بیشتر که در Pray تعبیه شده، از جمله شبکه‌های تبلیغاتی ایرانی. ممکن است چند برنامه از کار بیفتد.',
  'Filter lists: download community lists such as StevenBlack, HaGeZi or PersianBlocker for much wider coverage, or add your own list URL. You can also block single sites in Custom rules below.': 'فهرست‌های فیلتر: فهرست‌های جامعه مانند StevenBlack، HaGeZi یا PersianBlocker را برای پوشش بسیار گسترده‌تر دانلود کنید یا نشانی فهرست خودتان را اضافه کنید. همچنین می‌توانید سایت‌های تکی را در قوانین سفارشی پایین مسدود کنید.',
  'Limits: ads served from the same address as the content (most YouTube and in-app video ads) cannot be told apart and still show. Encrypted DNS inside an app can also bypass name-based blocking.': 'محدودیت‌ها: تبلیغاتی که از همان نشانی محتوا پخش می‌شوند (بیشتر تبلیغات یوتیوب و ویدیوهای درون برنامه) قابل تشخیص نیستند و همچنان نمایش داده می‌شوند. DNS رمزنگاری‌شده درون یک برنامه هم می‌تواند مسدودسازی مبتنی بر نام را دور بزند.',
  'Filter lists': 'فهرست‌های فیلتر',
  '{} enabled': '{} فعال',
  'Add filter list': 'افزودن فهرست فیلتر',
  'List URL': 'نشانی فهرست',
  'Hosts, plain domain or AdGuard-style list': 'فهرست hosts، دامنه‌ی ساده یا به سبک AdGuard',
  'Turn on the lists you want, then download them. Every domain in an enabled list is blocked while Pray is connected. More lists block more, but can break some sites and apps.': 'فهرست‌های دلخواه را روشن کنید و دانلود کنید. هر دامنه‌ی موجود در فهرست‌های فعال هنگام اتصال Pray مسدود می‌شود. فهرست‌های بیشتر موارد بیشتری را مسدود می‌کنند اما ممکن است برخی سایت‌ها و برنامه‌ها را خراب کنند.',
  'Add a list': 'افزودن فهرست',
  'Download enabled lists': 'دانلود فهرست‌های فعال',
  'Downloading…': 'در حال دانلود…',
  'Downloading {}%': 'در حال دانلود {}٪',
  '{} domains': '{} دامنه',
  '{} domains, updated {}': '{} دامنه، به‌روزرسانی {}',
  '{} domains ready.': '{} دامنه آماده است.',
  'Reconnect after updating to apply the new lists.': 'برای اعمال فهرست‌های جدید پس از به‌روزرسانی دوباره متصل شوید.',
  'Apps': 'برنامه‌ها',
  'Per-app proxy': 'پروکسی به‌ازای هر برنامه',
  'Choose which apps use the VPN': 'انتخاب برنامه‌هایی که از VPN استفاده می‌کنند',
  'Choose apps': 'انتخاب برنامه‌ها',
  '{} selected': '{} انتخاب شده',
  'Apps ({})': 'برنامه‌ها ({})',
  'Custom rules': 'قوانین سفارشی',
  'Through the proxy': 'از طریق پروکسی',
  'Direct': 'مستقیم',
  'Block': 'مسدود',
  'Blocked': 'مسدود',
  'Remove rule': 'حذف قانون',
  'Add a rule': 'افزودن قانون',
  'Add another rule': 'افزودن قانون دیگر',
  'Send a domain or IP through the proxy, direct, or block it': 'یک دامنه یا IP را از پروکسی عبور دهید، مستقیم کنید یا مسدود کنید',
  'Enter a domain, IP or CIDR': 'دامنه، IP یا CIDR وارد کنید',
  'Add rule': 'افزودن قانون',
  'Domain, IP or CIDR': 'دامنه، IP یا CIDR',
  'Cloudflare WARP': 'Cloudflare WARP',
  'WARP only': 'فقط WARP',
  'Server, then WARP': 'سرور، سپس WARP',
  'WARP for chosen sites': 'WARP برای سایت‌های انتخابی',
  'Use only your server': 'فقط از سرور خودتان استفاده کنید',
  'Send everything through Cloudflare WARP, no server needed': 'همه چیز را از Cloudflare WARP عبور دهید، بدون نیاز به سرور',
  'Your server first, then Cloudflare, so sites see a Cloudflare address': 'ابتدا سرور شما و سپس Cloudflare، تا سایت‌ها نشانی Cloudflare را ببینند',
  'Normal routing, but the sites you list leave through WARP': 'مسیریابی عادی، اما سایت‌هایی که فهرست می‌کنید از WARP خارج می‌شوند',
  'WARP endpoint': 'نقطه‌ی پایانی WARP',
  'Default {}': 'پیش‌فرض {}',
  'Sites that use WARP': 'سایت‌هایی که از WARP استفاده می‌کنند',
  'One per line, like openai.com or geosite:netflix': 'هر خط یکی، مانند openai.com یا geosite:netflix',
  '{} entries': '{} مورد',
  'Endpoint': 'نقطه‌ی پایانی',
  'WARP is a free Cloudflare tunnel. Pray can create a free WARP account for you and use it in three ways.': 'WARP یک تونل رایگان Cloudflare است. Pray می‌تواند یک حساب WARP رایگان برایتان بسازد و به سه روش از آن استفاده کند.',
  'WARP only: all traffic goes straight through Cloudflare. No server is needed, but WARP is blocked on some networks.': 'فقط WARP: همه‌ی ترافیک مستقیم از Cloudflare عبور می‌کند. به سرور نیازی نیست، اما WARP در برخی شبکه‌ها مسدود است.',
  'Server, then WARP: traffic goes through your server first and leaves from a Cloudflare address. This helps with sites that block server addresses, and hides your server address from those sites.': 'سرور، سپس WARP: ترافیک ابتدا از سرور شما می‌گذرد و از یک نشانی Cloudflare خارج می‌شود. این برای سایت‌هایی که نشانی سرورها را مسدود می‌کنند مفید است و نشانی سرور شما را از آن سایت‌ها پنهان می‌کند.',
  'WARP for chosen sites: everything uses your normal route, but the sites you list (for example AI services) go through WARP.': 'WARP برای سایت‌های انتخابی: همه چیز از مسیر عادی می‌رود، اما سایت‌هایی که فهرست می‌کنید (مثلاً سرویس‌های هوش مصنوعی) از WARP عبور می‌کنند.',
  'WARP hides your address from sites, it does not hide your traffic from Cloudflare.': 'WARP نشانی شما را از سایت‌ها پنهان می‌کند، اما ترافیک شما را از Cloudflare پنهان نمی‌کند.',
  'No WARP account': 'حساب WARP وجود ندارد',
  'WARP account ready': 'حساب WARP آماده است',
  'Tap to create a free account': 'برای ساخت حساب رایگان بزنید',
  'Tap the bin to remove it': 'برای حذف، سطل زباله را بزنید',
  'Remove account': 'حذف حساب',
  'Register a WARP account first (Routing, WARP).': 'ابتدا یک حساب WARP بسازید (مسیریابی، WARP).',
  'Add a server first.': 'ابتدا یک سرور اضافه کنید.',
  'Per-app proxy is on, but no apps are selected.': 'پروکسی به‌ازای برنامه روشن است اما هیچ برنامه‌ای انتخاب نشده.',
  'VPN permission was not granted.': 'مجوز VPN داده نشد.',
  'The VPN was turned off by Android.': 'VPN توسط اندروید خاموش شد.',
  'xray stopped unexpectedly. Check the log for details.': 'xray به‌طور غیرمنتظره متوقف شد. برای جزئیات گزارش را ببینید.',
  'Administrator permission was not granted.': 'مجوز مدیر داده نشد.',
  'xray did not create the TUN interface.': 'xray رابط TUN را نساخت.',
  'xray is already running.': 'xray از قبل در حال اجراست.',
  'No bundled xray for this platform.': 'xray داخلی برای این پلتفرم وجود ندارد.',
  'No geo data folder.': 'پوشه‌ی داده‌ی جغرافیایی وجود ندارد.',
  'Download failed': 'دانلود ناموفق بود',
  'Downloaded file is too small': 'فایل دانلودشده بیش از حد کوچک است',
  'The file is too large': 'فایل بیش از حد بزرگ است',
  'This is not a .pray file.': 'این یک فایل ‎.pray نیست.',
  'This .pray file is from a newer version.': 'این فایل ‎.pray مربوط به نسخه‌ی جدیدتری است.',
  'A password is required.': 'گذرواژه لازم است.',
  'Wrong password or damaged file.': 'گذرواژه اشتباه است یا فایل آسیب دیده.',
  'The file is damaged.': 'فایل آسیب دیده است.',
  'The file content is not valid.': 'محتوای فایل معتبر نیست.',
  'WARP registration timed out': 'ثبت‌نام WARP زمان‌بر شد',
  'WARP registration failed (HTTP {})': 'ثبت‌نام WARP ناموفق بود (HTTP {})',
  'Install zenity or kdialog to choose files.': 'برای انتخاب فایل zenity یا kdialog را نصب کنید.',
  'Add source': 'افزودن منبع',
  'Looking for servers…': 'در حال جستجوی سرور…',
  'Nothing could be downloaded. Check your internet connection and try again.': 'چیزی دانلود نشد. اتصال اینترنت را بررسی و دوباره تلاش کنید.',
  'Checking which ones work…': 'در حال بررسی اینکه کدام کار می‌کنند…',
  'No working server was found right now. Try again later.': 'فعلاً سرور کارآمدی پیدا نشد. بعداً دوباره تلاش کنید.',
  'Added {} server(s)': '{} سرور اضافه شد',
  'Sources': 'منابع',
  'Choose servers': 'انتخاب سرورها',
  'Free servers': 'سرورهای رایگان',
  'Find free servers': 'یافتن سرورهای رایگان',
  'Pray looks for free servers shared by volunteers, checks which ones work and adds the fastest ones for you.': 'Pray سرورهای رایگانی را که داوطلبان به اشتراک گذاشته‌اند پیدا می‌کند، کارآمدها را بررسی می‌کند و سریع‌ترین‌ها را برایتان اضافه می‌کند.',
  'Change where to look': 'تغییر محل جستجو',
  'Free servers are shared with many people. Do not use them for banking or private accounts.': 'سرورهای رایگان با افراد زیادی به اشتراک گذاشته می‌شوند. از آن‌ها برای بانک یا حساب‌های خصوصی استفاده نکنید.',
  'Add a source': 'افزودن منبع',
  'Restore the default sources': 'بازگرداندن منابع پیش‌فرض',
  'This can take a minute.': 'ممکن است یک دقیقه طول بکشد.',
  '{} working servers found': '{} سرور کارآمد پیدا شد',
  'Add the best {}': 'افزودن {} مورد برتر',
  'Let me choose': 'خودم انتخاب می‌کنم',
  '{} of {} selected': '{} از {} انتخاب شده',
  'Select all': 'انتخاب همه',
  'Deselect all': 'لغو انتخاب همه',
  'Tip: press and hold a row, then drag to select many.': 'نکته: روی یک ردیف نگه دارید و بکشید تا چند مورد انتخاب شود.',
  'Add {}': 'افزودن {}',
  'Appearance': 'ظاهر',
  'Auto': 'خودکار',
  'Latte': 'لاته',
  'Mocha': 'موکا',
  'Language': 'زبان',
  'System default': 'پیش‌فرض سیستم',
  'Network': 'شبکه',
  'Proxy port': 'پورت پروکسی',
  'SOCKS5 proxy, also available while TUN is on': 'پروکسی SOCKS5، در حالت TUN هم در دسترس است',
  'Allow LAN connections': 'اجازه‌ی اتصال از شبکه‌ی محلی',
  'Let other devices use the proxy': 'به دستگاه‌های دیگر اجازه‌ی استفاده از پروکسی را بدهید',
  'Startup': 'راه‌اندازی',
  'Connect on launch': 'اتصال هنگام اجرا',
  'Start the tunnel when Pray opens': 'هنگام باز شدن Pray تونل را راه‌اندازی کن',
  'Launch at login': 'اجرا هنگام ورود',
  'Start Pray with your session': 'Pray را با نشست کاربری شروع کن',
  'Core': 'هسته',
  'Geo data': 'داده‌ی جغرافیایی',
  'Download the latest geoip and geosite': 'دانلود جدیدترین geoip و geosite',
  'Last updated {}': 'آخرین به‌روزرسانی {}',
  'Geo data updated. Reconnect to use it.': 'داده‌ی جغرافیایی به‌روز شد. برای استفاده دوباره متصل شوید.',
  'Enter a port from {} to {}': 'پورتی از {} تا {} وارد کنید',
  'Version {}': 'نسخه‌ی {}',
  'Made with love by {}': 'ساخته‌شده با عشق توسط {}',
  'Links': 'پیوندها',
  'Built with': 'ساخته‌شده با',
  'The toolkit behind the interface': 'ابزار پشت رابط کاربری',
  'The language it is written in': 'زبانی که با آن نوشته شده',
  'The engine behind every connection': 'موتور پشت هر اتصال',
  'The Mocha and Latte palettes': 'پالت‌های Mocha و Latte',
  'The typeface, under the SIL Open Font License': 'فونت، تحت مجوز SIL Open Font',
  'Copy link': 'کپی لینک',
  'Couldn\'t open {}': 'باز کردن {} ممکن نشد',
  'Couldn\'t download: {}': 'دانلود ممکن نشد: {}',
  'What does this do?': 'این چه کاری می‌کند؟',
  'Got it': 'متوجه شدم',
  'Show': 'نمایش',
  'Failed: {}.': 'ناموفق: {}.',
  'HTTP {}': 'HTTP {}',
  'Delete {} servers?': '{} سرور حذف شوند؟',
  'Donate': 'حمایت مالی',
  'YouTube ads': 'تبلیغات یوتیوب',
  'Blocks YouTube and Google ad requests. Ads served inside the video itself still show.': 'درخواست‌های تبلیغاتی یوتیوب و گوگل را مسدود می‌کند. تبلیغاتی که داخل خود ویدیو پخش می‌شوند همچنان نمایش داده می‌شوند.',
  'Nothing is blocked.': 'هیچ چیز مسدود نمی‌شود.',
  'Blocks the well-known ad networks and trackers.': 'شبکه‌های تبلیغاتی و ردیاب‌های شناخته‌شده را مسدود می‌کند.',
  'Standard plus extra ads, trackers and analytics. A few apps may break.': 'استاندارد به‌علاوه‌ی تبلیغات، ردیاب‌ها و تحلیلگرهای بیشتر. ممکن است چند برنامه خراب شود.',
  'Renew WARP account': 'نوسازی حساب WARP',
  'Create a new free account. Use this if WARP stops working.': 'یک حساب رایگان جدید بسازید. اگر WARP از کار افتاد از این استفاده کنید.',
  'YouTube ads: blocks the ad servers YouTube and Google use for banner, display and some video ad requests. Most video ads come from the same servers as the video itself, so a few will remain. For complete YouTube ad blocking use an ad-free client.': 'تبلیغات یوتیوب: سرورهای تبلیغاتی را که یوتیوب و گوگل برای بنر، نمایشی و برخی درخواست‌های تبلیغ ویدیویی استفاده می‌کنند مسدود می‌کند. بیشتر تبلیغات ویدیویی از همان سرورهای خود ویدیو می‌آیند، پس چندتایی باقی می‌مانند. برای مسدودسازی کامل تبلیغات یوتیوب از یک کلاینت بدون تبلیغ استفاده کنید.',
  'Could not start the administrator helper (code {}).': 'راه‌اندازی دستیار مدیر ممکن نشد (کد {}).',
  'Latin and Cyrillic text, under the SIL Open Font License': 'متن لاتین و سیریلیک، تحت مجوز SIL Open Font',
  'Persian text, under the SIL Open Font License': 'متن فارسی، تحت مجوز SIL Open Font',
  'Chinese text, under the SIL Open Font License': 'متن چینی، تحت مجوز SIL Open Font',
  'Japanese text, under the SIL Open Font License': 'متن ژاپنی، تحت مجوز SIL Open Font',
  'DNS server': 'سرور DNS',
  'Encrypted DNS': 'DNS رمزگذاری‌شده',
  'Send lookups over HTTPS so nobody on the network can read them': 'جستجوها را از طریق HTTPS بفرست تا کسی در شبکه نتواند آن‌ها را بخواند',
  'Fake DNS': 'DNS جعلی',
  'Answer lookups inside the tunnel with placeholder addresses. TUN mode only': 'جستجوها را درون تونل با نشانی‌های جایگزین پاسخ بده. فقط حالت TUN',
  'DNS leak test': 'تست نشت DNS',
  'See which servers answer your DNS lookups': 'ببینید کدام سرورها به جستجوهای DNS شما پاسخ می‌دهند',
  'Custom': 'سفارشی',
  'Enter at least one DNS server': 'حداقل یک سرور DNS وارد کنید',
  'DNS server address': 'نشانی سرور DNS',
  'An IP like 9.9.9.9 or an https:// DoH address, separated by commas': 'یک IP مانند 9.9.9.9 یا نشانی DoH با https://، جدا شده با ویرگول',
  'Testing…': 'در حال آزمایش…',
  'The test failed. Check your connection.': 'آزمایش ناموفق بود. اتصال خود را بررسی کنید.',
  'Your IP': 'IP شما',
  'No DNS servers were reported.': 'هیچ سرور DNS گزارش نشد.',
  'DNS servers that answered': 'سرورهای DNS که پاسخ دادند',
  'Run again': 'اجرای دوباره',
  'Update available': 'به‌روزرسانی موجود است',
  'Version {} is available. You have {}.': 'نسخه {} منتشر شده است. نسخه شما {} است.',
  'Later': 'بعداً',
  'Download': 'دانلود',
  'How it works: before connecting to a site, an app asks a DNS server for its address. Whoever answers can see every site you visit, and on some networks can fake the answer.': 'طرز کار: برنامه قبل از اتصال به یک سایت، نشانی آن را از یک سرور DNS می‌پرسد. هر که پاسخ دهد می‌تواند همه سایت‌هایی را که می‌بینید ببیند و در برخی شبکه‌ها می‌تواند پاسخ را جعل کند.',
  'DNS server: who answers those lookups. System default uses your device\'s own DNS, which is usually your internet provider. Cloudflare, Google and Quad9 are public servers. Custom lets you enter your own.': 'سرور DNS: چه کسی به این جستجوها پاسخ می‌دهد. پیش‌فرض سیستم از DNS خود دستگاه استفاده می‌کند که معمولاً همان ارائه‌دهندهٔ اینترنت شماست. Cloudflare، Google و Quad9 سرورهای عمومی‌اند. در حالت سفارشی می‌توانید سرور خودتان را وارد کنید.',
  'Encrypted DNS: sends the lookups over HTTPS, so the network between you and the server cannot read or change them.': 'DNS رمزگذاری‌شده: جستجوها را از طریق HTTPS می‌فرستد تا شبکهٔ میان شما و سرور نتواند آن‌ها را بخواند یا تغییر دهد.',
  'Fake DNS: in TUN mode, answers lookups right inside the tunnel with placeholder addresses and swaps the real site name back in when the app connects. It can be faster and avoids DNS leaks, but a few apps may break.': 'DNS جعلی: در حالت TUN، جستجوها را درون تونل با نشانی‌های جایگزین پاسخ می‌دهد و هنگام اتصال برنامه، نام واقعی سایت را جایگزین می‌کند. می‌تواند سریع‌تر باشد و از نشت DNS جلوگیری می‌کند، اما چند برنامه ممکن است خراب شوند.',
  'DNS leak test: checks which servers really answer your lookups. If you see your own provider while connected, DNS is leaking.': 'تست نشت DNS: بررسی می‌کند کدام سرورها واقعاً به جستجوهای شما پاسخ می‌دهند. اگر هنگام اتصال، ارائه‌دهندهٔ خودتان را ببینید، DNS نشت می‌کند.',
};
