const Map<String, String> stringsZh = {
  'Home': '主页',
  'Servers': '服务器',
  'Routing': '路由',
  'Settings': '设置',
  'About': '关于',
  'Disconnected': '未连接',
  'Tap to connect': '点击连接',
  'Connecting': '连接中',
  'Connecting…': '连接中…',
  'Starting the tunnel': '正在启动隧道',
  'Connected': '已连接',
  'Connect': '连接',
  'Disconnect': '断开',
  'Quit': '退出',
  'Show {}': '显示 {}',
  '{} is connected': '{} 已连接',
  '{} is disconnected': '{} 已断开',
  'Your traffic is routed through the proxy.': '您的流量正通过代理转发。',
  'Your traffic is going directly.': '您的流量正在直连。',
  'Proxy': '代理',
  'TUN': 'TUN',
  'Down': '下载',
  'Up': '上传',
  'Ping': '延迟',
  'Mixed': '混合',
  'Copy address': '复制地址',
  'Copied {}': '已复制 {}',
  'Test latency': '测试延迟',
  'Free configs': '免费配置',
  'Share all servers': '分享所有服务器',
  'Add server': '添加服务器',
  'Sort servers': '服务器排序',
  'Oldest first': '最早添加',
  'Newest first': '最新添加',
  'Lowest ping': '延迟最低',
  'Name': '名称',
  'Protocol': '协议',
  'No servers yet. Tap + to add one.': '还没有服务器。点击 + 添加。',
  'Delete server?': '删除服务器？',
  'Cancel': '取消',
  'Delete': '删除',
  'Clipboard is empty': '剪贴板为空',
  'No share links found in the clipboard': '剪贴板中没有分享链接',
  'Added 1 server': '已添加 1 个服务器',
  'Added {} servers': '已添加 {} 个服务器',
  'Added {} server(s), {} line(s) had errors': '已添加 {} 个服务器，{} 行有错误',
  'No servers found': '未找到服务器',
  'Password': '密码',
  'File password': '文件密码',
  'Open': '打开',
  'Subscription URL': '订阅链接',
  'Import': '导入',
  'Paste from clipboard': '从剪贴板粘贴',
  'One or more vless, vmess, trojan or ss links': '一个或多个 vless、vmess、trojan 或 ss 链接',
  'Download a whole list of servers': '下载整个服务器列表',
  'Import .pray file': '导入 .pray 文件',
  'Servers shared by another Pray app': '来自其他 Pray 应用分享的服务器',
  'Scan QR code': '扫描二维码',
  'Use the camera': '使用相机',
  'QR scanning': '二维码扫描',
  '{} arrives with the Xray core.': '{} 将随 Xray 内核推出。',
  'Enter a valid address and port (1-65535).': '请输入有效的地址和端口 (1-65535)。',
  'Edit server': '编辑服务器',
  'Address': '地址',
  'Port': '端口',
  'UUID': 'UUID',
  'Save': '保存',
  'Add': '添加',
  'Remove': '移除',
  'Done': '完成',
  'Close': '关闭',
  'Copy': '复制',
  'Link': '链接',
  'File': '文件',
  'Search': '搜索',
  'More': '更多',
  'Share': '分享',
  'Edit': '编辑',
  'Pin to top': '置顶',
  'Unpin': '取消置顶',
  'Enter a password or turn protection off.': '请输入密码或关闭保护。',
  'Saved {}': '已保存 {}',
  'Save {}': '保存 {}',
  'Link copied': '链接已复制',
  'Links copied': '链接已复制',
  'Protect with a password': '使用密码保护',
  'Only people with the password can open it': '只有知道密码的人才能打开',
  'Any Pray app can open it': '任何 Pray 应用都能打开',
  'Too long for a QR code': '内容过长，无法生成二维码',
  'Where traffic goes': '流量去向',
  'Proxy everything': '全部走代理',
  'Bypass local network': '绕过局域网',
  'Bypass Iran': '绕过伊朗',
  'All traffic goes through the server': '所有流量都经过服务器',
  'Local addresses connect directly': '本地地址直连',
  'Iranian sites and IPs connect directly': '伊朗网站和 IP 直连',
  ' — disconnect to change': ' — 断开后才能更改',
  'Proxy everything: all traffic goes through the server.': '全部走代理：所有流量都经过服务器。',
  'Bypass local network: only addresses on your own network (router, printers, other devices) connect directly. Everything else goes through the server.': '绕过局域网：只有您自己网络中的地址（路由器、打印机、其他设备）直连，其余都经过服务器。',
  'Bypass Iran: Iranian sites (.ir and known Iranian domains) and Iranian IP addresses connect directly, as well as your local network. Everything else goes through the server.': '绕过伊朗：伊朗网站（.ir 和已知的伊朗域名）、伊朗 IP 地址以及局域网直连，其余都经过服务器。',
  'Ad blocking': '广告拦截',
  'Off': '关闭',
  'Standard': '标准',
  'Strict': '严格',
  'How it works: while connected, Pray looks at the name of every site or server an app tries to reach and drops the connection if the name is on a block list. Nothing is installed on your device and no traffic is read.': '工作原理：连接期间，Pray 会检查应用要访问的每个网站或服务器的名称，如果名称在拦截列表中就断开连接。不会在设备上安装任何东西，也不会读取流量内容。',
  'Off: nothing is blocked.': '关闭：不拦截任何内容。',
  'Standard: blocks the well-known ad networks and trackers from the built-in geo data.': '标准：根据内置的 geo 数据拦截知名的广告网络和跟踪器。',
  'Strict: Standard plus extra ad, tracker and analytics domains built into Pray, including Iranian ad networks. A few apps may stop working.': '严格：在标准基础上，加上 Pray 内置的更多广告、跟踪和统计域名，包括伊朗广告网络。少数应用可能无法使用。',
  'Filter lists: download community lists such as StevenBlack, HaGeZi or PersianBlocker for much wider coverage, or add your own list URL. You can also block single sites in Custom rules below.': '过滤列表：下载 StevenBlack、HaGeZi 或 PersianBlocker 等社区列表可大幅扩大拦截范围，也可以添加自己的列表链接。还可以在下方的自定义规则中拦截单个网站。',
  'Limits: ads served from the same address as the content (most YouTube and in-app video ads) cannot be told apart and still show. Encrypted DNS inside an app can also bypass name-based blocking.': '局限：与内容来自同一地址的广告（大多数 YouTube 和应用内视频广告）无法区分，仍会显示。应用内部的加密 DNS 也可能绕过基于名称的拦截。',
  'Filter lists': '过滤列表',
  '{} enabled': '已启用 {} 个',
  'Add filter list': '添加过滤列表',
  'List URL': '列表链接',
  'Hosts, plain domain or AdGuard-style list': 'hosts、纯域名或 AdGuard 格式的列表',
  'Turn on the lists you want, then download them. Every domain in an enabled list is blocked while Pray is connected. More lists block more, but can break some sites and apps.': '开启需要的列表并下载。连接 Pray 时，已启用列表中的每个域名都会被拦截。列表越多拦截越多，但可能导致部分网站和应用无法使用。',
  'Add a list': '添加列表',
  'Download enabled lists': '下载已启用的列表',
  'Downloading…': '正在下载…',
  'Downloading {}%': '正在下载 {}%',
  '{} domains': '{} 个域名',
  '{} domains, updated {}': '{} 个域名，更新于 {}',
  '{} domains ready.': '已准备 {} 个域名。',
  'Reconnect after updating to apply the new lists.': '更新后请重新连接以应用新列表。',
  'Apps': '应用',
  'Per-app proxy': '分应用代理',
  'Choose which apps use the VPN': '选择使用 VPN 的应用',
  'Choose apps': '选择应用',
  '{} selected': '已选 {} 个',
  'Apps ({})': '应用 ({})',
  'Custom rules': '自定义规则',
  'Through the proxy': '经代理',
  'Direct': '直连',
  'Block': '拦截',
  'Blocked': '拦截',
  'Remove rule': '删除规则',
  'Add a rule': '添加规则',
  'Add another rule': '再添加一条规则',
  'Send a domain or IP through the proxy, direct, or block it': '让域名或 IP 走代理、直连或被拦截',
  'Enter a domain, IP or CIDR': '请输入域名、IP 或 CIDR',
  'Add rule': '添加规则',
  'Domain, IP or CIDR': '域名、IP 或 CIDR',
  'Cloudflare WARP': 'Cloudflare WARP',
  'WARP only': '仅 WARP',
  'Server, then WARP': '先服务器，再 WARP',
  'WARP for chosen sites': '指定网站使用 WARP',
  'Use only your server': '仅使用您的服务器',
  'Send everything through Cloudflare WARP, no server needed': '全部经 Cloudflare WARP 转发，无需服务器',
  'Your server first, then Cloudflare, so sites see a Cloudflare address': '先经过您的服务器再经 Cloudflare，网站看到的是 Cloudflare 地址',
  'Normal routing, but the sites you list leave through WARP': '正常路由，但您列出的网站通过 WARP 出站',
  'WARP endpoint': 'WARP 端点',
  'Default {}': '默认 {}',
  'Sites that use WARP': '使用 WARP 的网站',
  'One per line, like openai.com or geosite:netflix': '每行一个，例如 openai.com 或 geosite:netflix',
  '{} entries': '{} 条',
  'Endpoint': '端点',
  'WARP is a free Cloudflare tunnel. Pray can create a free WARP account for you and use it in three ways.': 'WARP 是 Cloudflare 的免费隧道。Pray 可以为您创建免费的 WARP 账户，并以三种方式使用。',
  'WARP only: all traffic goes straight through Cloudflare. No server is needed, but WARP is blocked on some networks.': '仅 WARP：所有流量直接经过 Cloudflare。无需服务器，但部分网络会封锁 WARP。',
  'Server, then WARP: traffic goes through your server first and leaves from a Cloudflare address. This helps with sites that block server addresses, and hides your server address from those sites.': '先服务器，再 WARP：流量先经过您的服务器，再从 Cloudflare 地址出站。这有助于访问封锁服务器地址的网站，也能向这些网站隐藏您的服务器地址。',
  'WARP for chosen sites: everything uses your normal route, but the sites you list (for example AI services) go through WARP.': '指定网站使用 WARP：其余流量走正常路线，您列出的网站（例如 AI 服务）经由 WARP。',
  'WARP hides your address from sites, it does not hide your traffic from Cloudflare.': 'WARP 会向网站隐藏您的地址，但不会向 Cloudflare 隐藏您的流量。',
  'No WARP account': '没有 WARP 账户',
  'WARP account ready': 'WARP 账户已就绪',
  'Tap to create a free account': '点击创建免费账户',
  'Tap the bin to remove it': '点击垃圾桶即可删除',
  'Remove account': '删除账户',
  'Register a WARP account first (Routing, WARP).': '请先注册 WARP 账户（路由 → WARP）。',
  'Add a server first.': '请先添加服务器。',
  'Per-app proxy is on, but no apps are selected.': '已开启分应用代理，但未选择任何应用。',
  'VPN permission was not granted.': '未授予 VPN 权限。',
  'The VPN was turned off by Android.': 'VPN 已被 Android 关闭。',
  'xray stopped unexpectedly. Check the log for details.': 'xray 意外停止。请查看日志了解详情。',
  'Administrator permission was not granted.': '未授予管理员权限。',
  'xray did not create the TUN interface.': 'xray 未能创建 TUN 接口。',
  'xray is already running.': 'xray 已在运行。',
  'No bundled xray for this platform.': '此平台没有内置 xray。',
  'No geo data folder.': '没有 geo 数据文件夹。',
  'Download failed': '下载失败',
  'Downloaded file is too small': '下载的文件太小',
  'The file is too large': '文件太大',
  'This is not a .pray file.': '这不是 .pray 文件。',
  'This .pray file is from a newer version.': '此 .pray 文件来自更新的版本。',
  'A password is required.': '需要密码。',
  'Wrong password or damaged file.': '密码错误或文件已损坏。',
  'The file is damaged.': '文件已损坏。',
  'The file content is not valid.': '文件内容无效。',
  'WARP registration timed out': 'WARP 注册超时',
  'WARP registration failed (HTTP {})': 'WARP 注册失败 (HTTP {})',
  'Install zenity or kdialog to choose files.': '请安装 zenity 或 kdialog 以选择文件。',
  'Add source': '添加来源',
  'Looking for servers…': '正在查找服务器…',
  'Nothing could be downloaded. Check your internet connection and try again.': '无法下载任何内容。请检查网络连接后重试。',
  'Checking which ones work…': '正在检测哪些可用…',
  'No working server was found right now. Try again later.': '目前没有找到可用的服务器，请稍后再试。',
  'Added {} server(s)': '已添加 {} 个服务器',
  'Sources': '来源',
  'Choose servers': '选择服务器',
  'Free servers': '免费服务器',
  'Find free servers': '查找免费服务器',
  'Pray looks for free servers shared by volunteers, checks which ones work and adds the fastest ones for you.': 'Pray 会查找志愿者分享的免费服务器，检测哪些可用，并为您添加最快的几个。',
  'Change where to look': '更改查找来源',
  'Free servers are shared with many people. Do not use them for banking or private accounts.': '免费服务器由很多人共用，请勿用于网银或私人账户。',
  'Add a source': '添加来源',
  'Restore the default sources': '恢复默认来源',
  'This can take a minute.': '这可能需要一分钟。',
  '{} working servers found': '找到 {} 个可用服务器',
  'Add the best {}': '添加最好的 {} 个',
  'Let me choose': '我自己选',
  '{} of {} selected': '已选 {} / {}',
  'Select all': '全选',
  'Deselect all': '取消全选',
  'Tip: press and hold a row, then drag to select many.': '提示：长按一行再拖动即可多选。',
  'Add {}': '添加 {}',
  'Appearance': '外观',
  'Auto': '自动',
  'Latte': 'Latte',
  'Mocha': 'Mocha',
  'Language': '语言',
  'System default': '跟随系统',
  'Network': '网络',
  'Proxy port': '代理端口',
  'SOCKS5 proxy, also available while TUN is on': 'SOCKS5 代理，开启 TUN 时同样可用',
  'Allow LAN connections': '允许局域网连接',
  'Let other devices use the proxy': '允许其他设备使用此代理',
  'Startup': '启动',
  'Connect on launch': '启动时连接',
  'Start the tunnel when Pray opens': 'Pray 打开时启动隧道',
  'Launch at login': '登录时启动',
  'Start Pray with your session': '随会话启动 Pray',
  'Core': '内核',
  'Geo data': 'Geo 数据',
  'Download the latest geoip and geosite': '下载最新的 geoip 和 geosite',
  'Last updated {}': '最后更新 {}',
  'Geo data updated. Reconnect to use it.': 'Geo 数据已更新。重新连接后生效。',
  'Enter a port from {} to {}': '请输入 {} 到 {} 之间的端口',
  'Version {}': '版本 {}',
  'Made with love by {}': '{} 用心打造',
  'Links': '链接',
  'Built with': '构建所用',
  'The toolkit behind the interface': '界面背后的工具包',
  'The language it is written in': '所用的编程语言',
  'The engine behind every connection': '每个连接背后的引擎',
  'The Mocha and Latte palettes': 'Mocha 和 Latte 配色',
  'The typeface, under the SIL Open Font License': '字体，采用 SIL Open Font License',
  'Copy link': '复制链接',
  'Couldn\'t open {}': '无法打开 {}',
  'Couldn\'t download: {}': '无法下载：{}',
  'What does this do?': '这是做什么的？',
  'Got it': '知道了',
  'Show': '显示',
  'Failed: {}.': '失败：{}。',
  'HTTP {}': 'HTTP {}',
  'Delete {} servers?': '删除 {} 个服务器？',
  'Donate': '捐赠',
  'YouTube ads': 'YouTube 广告',
  'Blocks YouTube and Google ad requests. Ads served inside the video itself still show.': '拦截 YouTube 和 Google 的广告请求。视频内嵌的广告仍会显示。',
  'Nothing is blocked.': '不拦截任何内容。',
  'Blocks the well-known ad networks and trackers.': '拦截知名的广告网络和跟踪器。',
  'Standard plus extra ads, trackers and analytics. A few apps may break.': '标准基础上再拦截更多广告、跟踪和统计。少数应用可能无法使用。',
  'Renew WARP account': '更新 WARP 账户',
  'Create a new free account. Use this if WARP stops working.': '创建新的免费账户。WARP 无法使用时请使用此项。',
  'YouTube ads: blocks the ad servers YouTube and Google use for banner, display and some video ad requests. Most video ads come from the same servers as the video itself, so a few will remain. For complete YouTube ad blocking use an ad-free client.': 'YouTube 广告：拦截 YouTube 和 Google 用于横幅、展示及部分视频广告请求的广告服务器。大多数视频广告与视频本身来自同一服务器，因此仍会残留一些。如需彻底屏蔽 YouTube 广告，请使用无广告的客户端。',
  'Could not start the administrator helper (code {}).': '无法启动管理员辅助程序（代码 {}）。',
  'Latin and Cyrillic text, under the SIL Open Font License': '拉丁和西里尔文字，采用 SIL Open Font License',
  'Persian text, under the SIL Open Font License': '波斯文，采用 SIL Open Font License',
  'Chinese text, under the SIL Open Font License': '中文，采用 SIL Open Font License',
  'Japanese text, under the SIL Open Font License': '日文，采用 SIL Open Font License',
  'DNS server': 'DNS 服务器',
  'Encrypted DNS': '加密 DNS',
  'Send lookups over HTTPS so nobody on the network can read them': '通过 HTTPS 发送查询，网络上的任何人都无法读取',
  'Fake DNS': 'Fake DNS',
  'Answer lookups inside the tunnel with placeholder addresses. TUN mode only': '在隧道内用占位地址应答查询。仅限 TUN 模式',
  'DNS leak test': 'DNS 泄漏测试',
  'See which servers answer your DNS lookups': '查看哪些服务器在应答你的 DNS 查询',
  'Custom': '自定义',
  'Enter at least one DNS server': '请至少输入一个 DNS 服务器',
  'DNS server address': 'DNS 服务器地址',
  'An IP like 9.9.9.9 or an https:// DoH address, separated by commas': '如 9.9.9.9 的 IP，或 https:// 开头的 DoH 地址，用逗号分隔',
  'Testing…': '测试中…',
  'The test failed. Check your connection.': '测试失败，请检查网络连接。',
  'Your IP': '你的 IP',
  'No DNS servers were reported.': '未检测到 DNS 服务器。',
  'DNS servers that answered': '应答的 DNS 服务器',
  'Run again': '重新运行',
  'Update available': '有可用更新',
  'Version {} is available. You have {}.': '版本 {} 已发布，你当前为 {}。',
  'Later': '稍后',
  'Download': '下载',
  'How it works: before connecting to a site, an app asks a DNS server for its address. Whoever answers can see every site you visit, and on some networks can fake the answer.': '工作原理：应用在连接网站之前，会向 DNS 服务器询问它的地址。应答者能看到你访问的每个网站，在某些网络上还能伪造应答。',
  'DNS server: who answers those lookups. System default uses your device\'s own DNS, which is usually your internet provider. Cloudflare, Google and Quad9 are public servers. Custom lets you enter your own.': 'DNS 服务器：由谁来应答这些查询。系统默认使用设备自身的 DNS，通常就是你的网络运营商。Cloudflare、Google 和 Quad9 是公共服务器。选择自定义可输入你自己的服务器。',
  'Encrypted DNS: sends the lookups over HTTPS, so the network between you and the server cannot read or change them.': '加密 DNS：通过 HTTPS 发送查询，你与服务器之间的网络无法读取或篡改。',
  'Fake DNS: in TUN mode, answers lookups right inside the tunnel with placeholder addresses and swaps the real site name back in when the app connects. It can be faster and avoids DNS leaks, but a few apps may break.': 'Fake DNS：在 TUN 模式下，直接在隧道内用占位地址应答查询，并在应用连接时换回真实的网站名称。可能更快，也能避免 DNS 泄漏，但少数应用可能无法使用。',
  'DNS leak test: checks which servers really answer your lookups. If you see your own provider while connected, DNS is leaking.': 'DNS 泄漏测试：检查究竟哪些服务器在应答你的查询。如果连接时看到的是你自己的运营商，说明 DNS 正在泄漏。',
};
