const Map<String, String> stringsJa = {
  'Home': 'ホーム',
  'Servers': 'サーバー',
  'Routing': 'ルーティング',
  'Settings': '設定',
  'About': '情報',
  'Disconnected': '未接続',
  'Tap to connect': 'タップして接続',
  'Connecting': '接続中',
  'Connecting…': '接続中…',
  'Starting the tunnel': 'トンネルを開始中',
  'Connected': '接続済み',
  'Connect': '接続',
  'Disconnect': '切断',
  'Quit': '終了',
  'Show {}': '{} を表示',
  '{} is connected': '{} に接続しました',
  '{} is disconnected': '{} を切断しました',
  'Your traffic is routed through the proxy.': '通信はプロキシ経由です。',
  'Your traffic is going directly.': '通信は直接送信されています。',
  'Proxy': 'プロキシ',
  'TUN': 'TUN',
  'Down': 'ダウンロード',
  'Up': 'アップロード',
  'Ping': 'Ping',
  'Mixed': 'ミックス',
  'Copy address': 'アドレスをコピー',
  'Copied {}': '{} をコピーしました',
  'Test latency': '遅延をテスト',
  'Free configs': '無料の設定',
  'Share all servers': 'すべてのサーバーを共有',
  'Add server': 'サーバーを追加',
  'Sort servers': 'サーバーを並べ替え',
  'Oldest first': '古い順',
  'Newest first': '新しい順',
  'Lowest ping': 'Ping が低い順',
  'Name': '名前',
  'Protocol': 'プロトコル',
  'No servers yet. Tap + to add one.': 'サーバーがありません。+ をタップして追加します。',
  'Delete server?': 'サーバーを削除しますか？',
  'Cancel': 'キャンセル',
  'Delete': '削除',
  'Clipboard is empty': 'クリップボードは空です',
  'No share links found in the clipboard': 'クリップボードに共有リンクがありません',
  'Added 1 server': 'サーバーを 1 件追加しました',
  'Added {} servers': 'サーバーを {} 件追加しました',
  'Added {} server(s), {} line(s) had errors': 'サーバーを {} 件追加、{} 行でエラー',
  'No servers found': 'サーバーが見つかりません',
  'Password': 'パスワード',
  'File password': 'ファイルのパスワード',
  'Open': '開く',
  'Subscription URL': 'サブスクリプション URL',
  'Import': 'インポート',
  'Paste from clipboard': 'クリップボードから貼り付け',
  'One or more vless, vmess, trojan or ss links': 'vless、vmess、trojan、ss のリンク（複数可）',
  'Download a whole list of servers': 'サーバーの一覧をまとめてダウンロード',
  'Import .pray file': '「.pray」ファイルをインポート',
  'Servers shared by another Pray app': '他の Pray アプリから共有されたサーバー',
  'Scan QR code': 'QR コードをスキャン',
  'Use the camera': 'カメラを使用',
  'QR scanning': 'QR スキャン',
  '{} arrives with the Xray core.': '{} は Xray コアとともに提供されます。',
  'Enter a valid address and port (1-65535).': '有効なアドレスとポート (1-65535) を入力してください。',
  'Edit server': 'サーバーを編集',
  'Address': 'アドレス',
  'Port': 'ポート',
  'UUID': 'UUID',
  'Save': '保存',
  'Add': '追加',
  'Remove': '削除',
  'Done': '完了',
  'Close': '閉じる',
  'Copy': 'コピー',
  'Link': 'リンク',
  'File': 'ファイル',
  'Search': '検索',
  'More': 'その他',
  'Share': '共有',
  'Edit': '編集',
  'Pin to top': '先頭に固定',
  'Unpin': '固定を解除',
  'Enter a password or turn protection off.': 'パスワードを入力するか、保護をオフにしてください。',
  'Saved {}': '{} を保存しました',
  'Save {}': '{} を保存',
  'Link copied': 'リンクをコピーしました',
  'Links copied': 'リンクをコピーしました',
  'Protect with a password': 'パスワードで保護',
  'Only people with the password can open it': 'パスワードを知っている人だけが開けます',
  'Any Pray app can open it': 'どの Pray アプリでも開けます',
  'Too long for a QR code': 'QR コードには長すぎます',
  'Where traffic goes': '通信の経路',
  'Proxy everything': 'すべてプロキシ経由',
  'Bypass local network': 'ローカルネットワークは直結',
  'Bypass Iran': 'イランは直結',
  'All traffic goes through the server': 'すべての通信をサーバー経由にします',
  'Local addresses connect directly': 'ローカルアドレスは直接接続します',
  'Iranian sites and IPs connect directly': 'イランのサイトと IP は直接接続します',
  ' — disconnect to change': ' — 変更するには切断してください',
  'Proxy everything: all traffic goes through the server.': 'すべてプロキシ経由：すべての通信がサーバーを通ります。',
  'Bypass local network: only addresses on your own network (router, printers, other devices) connect directly. Everything else goes through the server.': 'ローカルネットワークは直結：自分のネットワーク内のアドレス（ルーター、プリンター、他のデバイス）だけを直接接続し、残りはサーバー経由にします。',
  'Bypass Iran: Iranian sites (.ir and known Iranian domains) and Iranian IP addresses connect directly, as well as your local network. Everything else goes through the server.': 'イランは直結：イランのサイト（.ir や既知のイランのドメイン）、イランの IP アドレス、ローカルネットワークを直接接続し、残りはサーバー経由にします。',
  'Ad blocking': '広告ブロック',
  'Off': 'オフ',
  'Standard': '標準',
  'Strict': '厳格',
  'How it works: while connected, Pray looks at the name of every site or server an app tries to reach and drops the connection if the name is on a block list. Nothing is installed on your device and no traffic is read.': '仕組み：接続中、Pray はアプリがアクセスしようとするサイトやサーバーの名前を確認し、ブロックリストに載っていれば接続を切ります。端末には何もインストールされず、通信内容は読み取られません。',
  'Off: nothing is blocked.': 'オフ：何もブロックしません。',
  'Standard: blocks the well-known ad networks and trackers from the built-in geo data.': '標準：内蔵の geo データにある有名な広告ネットワークとトラッカーをブロックします。',
  'Strict: Standard plus extra ad, tracker and analytics domains built into Pray, including Iranian ad networks. A few apps may stop working.': '厳格：標準に加えて、Pray に内蔵された広告・トラッカー・解析のドメイン（イランの広告ネットワークを含む）もブロックします。一部のアプリが動かなくなることがあります。',
  'Filter lists: download community lists such as StevenBlack, HaGeZi or PersianBlocker for much wider coverage, or add your own list URL. You can also block single sites in Custom rules below.': 'フィルターリスト：StevenBlack、HaGeZi、PersianBlocker などのコミュニティリストをダウンロードすると、ブロック範囲が大きく広がります。独自のリスト URL も追加できます。個別のサイトは下のカスタムルールでブロックできます。',
  'Limits: ads served from the same address as the content (most YouTube and in-app video ads) cannot be told apart and still show. Encrypted DNS inside an app can also bypass name-based blocking.': '制限：コンテンツと同じアドレスから配信される広告（YouTube やアプリ内の動画広告の大半）は区別できず、表示されます。アプリ内の暗号化 DNS も名前ベースのブロックを回避することがあります。',
  'Filter lists': 'フィルターリスト',
  '{} enabled': '{} 件を有効化',
  'Add filter list': 'フィルターリストを追加',
  'List URL': 'リスト URL',
  'Hosts, plain domain or AdGuard-style list': 'hosts、ドメインのみ、または AdGuard 形式のリスト',
  'Turn on the lists you want, then download them. Every domain in an enabled list is blocked while Pray is connected. More lists block more, but can break some sites and apps.': '使いたいリストをオンにしてダウンロードします。Pray の接続中は、有効なリストにあるすべてのドメインがブロックされます。リストを増やすほどブロックも増えますが、一部のサイトやアプリが動かなくなることがあります。',
  'Add a list': 'リストを追加',
  'Download enabled lists': '有効なリストをダウンロード',
  'Downloading…': 'ダウンロード中…',
  'Downloading {}%': 'ダウンロード中 {}%',
  '{} domains': '{} ドメイン',
  '{} domains, updated {}': '{} ドメイン、更新日 {}',
  '{} domains ready.': '{} ドメインの準備ができました。',
  'Reconnect after updating to apply the new lists.': '更新後に再接続すると新しいリストが反映されます。',
  'Apps': 'アプリ',
  'Per-app proxy': 'アプリ別プロキシ',
  'Choose which apps use the VPN': 'VPN を使うアプリを選択',
  'Choose apps': 'アプリを選択',
  '{} selected': '{} 件を選択',
  'Apps ({})': 'アプリ ({})',
  'Custom rules': 'カスタムルール',
  'Through the proxy': 'プロキシ経由',
  'Direct': '直接',
  'Block': 'ブロック',
  'Blocked': 'ブロック',
  'Remove rule': 'ルールを削除',
  'Add a rule': 'ルールを追加',
  'Add another rule': 'ルールをさらに追加',
  'Send a domain or IP through the proxy, direct, or block it': 'ドメインや IP をプロキシ経由・直接・ブロックに振り分けます',
  'Enter a domain, IP or CIDR': 'ドメイン、IP、CIDR を入力してください',
  'Add rule': 'ルールを追加',
  'Domain, IP or CIDR': 'ドメイン、IP、CIDR',
  'Cloudflare WARP': 'Cloudflare WARP',
  'WARP only': 'WARP のみ',
  'Server, then WARP': 'サーバー → WARP',
  'WARP for chosen sites': '指定サイトのみ WARP',
  'Use only your server': '自分のサーバーのみ使用',
  'Send everything through Cloudflare WARP, no server needed': 'すべて Cloudflare WARP 経由（サーバー不要）',
  'Your server first, then Cloudflare, so sites see a Cloudflare address': 'まず自分のサーバー、次に Cloudflare を通り、サイトには Cloudflare のアドレスが見えます',
  'Normal routing, but the sites you list leave through WARP': '通常のルーティングで、指定したサイトだけ WARP 経由にします',
  'WARP endpoint': 'WARP エンドポイント',
  'Default {}': '既定: {}',
  'Sites that use WARP': 'WARP を使うサイト',
  'One per line, like openai.com or geosite:netflix': '1 行に 1 件（例：openai.com、geosite:netflix）',
  '{} entries': '{} 件',
  'Endpoint': 'エンドポイント',
  'WARP is a free Cloudflare tunnel. Pray can create a free WARP account for you and use it in three ways.': 'WARP は Cloudflare の無料トンネルです。Pray は無料の WARP アカウントを作成し、3 通りの方法で使えます。',
  'WARP only: all traffic goes straight through Cloudflare. No server is needed, but WARP is blocked on some networks.': 'WARP のみ：すべての通信が直接 Cloudflare を通ります。サーバーは不要ですが、WARP がブロックされているネットワークもあります。',
  'Server, then WARP: traffic goes through your server first and leaves from a Cloudflare address. This helps with sites that block server addresses, and hides your server address from those sites.': 'サーバー → WARP：通信はまず自分のサーバーを通り、Cloudflare のアドレスから出ていきます。サーバーのアドレスをブロックするサイトに有効で、サーバーのアドレスをそのサイトから隠せます。',
  'WARP for chosen sites: everything uses your normal route, but the sites you list (for example AI services) go through WARP.': '指定サイトのみ WARP：通常は普段の経路を使い、指定したサイト（AI サービスなど）だけ WARP を通します。',
  'WARP hides your address from sites, it does not hide your traffic from Cloudflare.': 'WARP はサイトからあなたのアドレスを隠しますが、Cloudflare には通信内容が見えます。',
  'No WARP account': 'WARP アカウントなし',
  'WARP account ready': 'WARP アカウントの準備完了',
  'Tap to create a free account': 'タップして無料アカウントを作成',
  'Tap the bin to remove it': 'ゴミ箱をタップして削除',
  'Remove account': 'アカウントを削除',
  'Register a WARP account first (Routing, WARP).': '先に WARP アカウントを登録してください（ルーティング → WARP）。',
  'Add a server first.': '先にサーバーを追加してください。',
  'Per-app proxy is on, but no apps are selected.': 'アプリ別プロキシがオンですが、アプリが選択されていません。',
  'VPN permission was not granted.': 'VPN の権限が許可されませんでした。',
  'The VPN was turned off by Android.': 'VPN が Android によってオフにされました。',
  'xray stopped unexpectedly. Check the log for details.': 'xray が予期せず停止しました。詳細はログを確認してください。',
  'Administrator permission was not granted.': '管理者権限が許可されませんでした。',
  'xray did not create the TUN interface.': 'xray が TUN インターフェースを作成できませんでした。',
  'xray is already running.': 'xray はすでに実行中です。',
  'No bundled xray for this platform.': 'このプラットフォーム用の xray は同梱されていません。',
  'No geo data folder.': 'geo データのフォルダーがありません。',
  'Download failed': 'ダウンロードに失敗しました',
  'Downloaded file is too small': 'ダウンロードしたファイルが小さすぎます',
  'The file is too large': 'ファイルが大きすぎます',
  'This is not a .pray file.': 'これは .pray ファイルではありません。',
  'This .pray file is from a newer version.': 'この .pray ファイルは新しいバージョンのものです。',
  'A password is required.': 'パスワードが必要です。',
  'Wrong password or damaged file.': 'パスワードが違うか、ファイルが壊れています。',
  'The file is damaged.': 'ファイルが壊れています。',
  'The file content is not valid.': 'ファイルの内容が無効です。',
  'WARP registration timed out': 'WARP の登録がタイムアウトしました',
  'WARP registration failed (HTTP {})': 'WARP の登録に失敗しました (HTTP {})',
  'Install zenity or kdialog to choose files.': 'ファイルを選ぶには zenity または kdialog をインストールしてください。',
  'Add source': 'ソースを追加',
  'Looking for servers…': 'サーバーを探しています…',
  'Nothing could be downloaded. Check your internet connection and try again.': '何もダウンロードできませんでした。インターネット接続を確認して、もう一度お試しください。',
  'Checking which ones work…': '動作するものを確認しています…',
  'No working server was found right now. Try again later.': '現在使えるサーバーが見つかりません。後でもう一度お試しください。',
  'Added {} server(s)': 'サーバーを {} 件追加しました',
  'Sources': 'ソース',
  'Choose servers': 'サーバーを選択',
  'Free servers': '無料サーバー',
  'Find free servers': '無料サーバーを探す',
  'Pray looks for free servers shared by volunteers, checks which ones work and adds the fastest ones for you.': 'Pray はボランティアが共有している無料サーバーを探し、動作するものを確認して、最速のものを追加します。',
  'Change where to look': '検索先を変更',
  'Free servers are shared with many people. Do not use them for banking or private accounts.': '無料サーバーは多くの人と共有されます。ネットバンキングや個人アカウントには使わないでください。',
  'Add a source': 'ソースを追加',
  'Restore the default sources': '既定のソースに戻す',
  'This can take a minute.': '1 分ほどかかることがあります。',
  '{} working servers found': '動作するサーバーが {} 件見つかりました',
  'Add the best {}': '上位 {} 件を追加',
  'Let me choose': '自分で選ぶ',
  '{} of {} selected': '{} / {} 件を選択',
  'Select all': 'すべて選択',
  'Deselect all': 'すべて選択解除',
  'Tip: press and hold a row, then drag to select many.': 'ヒント：行を長押ししてドラッグすると、まとめて選択できます。',
  'Add {}': '{} 件を追加',
  'Appearance': '外観',
  'Auto': '自動',
  'Latte': 'Latte',
  'Mocha': 'Mocha',
  'Language': '言語',
  'System default': 'システムの設定',
  'Network': 'ネットワーク',
  'Proxy port': 'プロキシポート',
  'SOCKS5 proxy, also available while TUN is on': 'SOCKS5 プロキシ（TUN オン時も利用可）',
  'Allow LAN connections': 'LAN 接続を許可',
  'Let other devices use the proxy': '他のデバイスがプロキシを使えるようにします',
  'Startup': '起動',
  'Connect on launch': '起動時に接続',
  'Start the tunnel when Pray opens': 'Pray を開いたときにトンネルを開始',
  'Launch at login': 'ログイン時に起動',
  'Start Pray with your session': 'セッション開始時に Pray を起動',
  'Core': 'コア',
  'Geo data': 'Geo データ',
  'Download the latest geoip and geosite': '最新の geoip と geosite をダウンロード',
  'Last updated {}': '最終更新 {}',
  'Geo data updated. Reconnect to use it.': 'Geo データを更新しました。再接続すると反映されます。',
  'Enter a port from {} to {}': '{} から {} のポートを入力してください',
  'Version {}': 'バージョン {}',
  'Made with love by {}': '{} が愛を込めて制作',
  'Links': 'リンク',
  'Built with': '使用技術',
  'The toolkit behind the interface': '画面を支えるツールキット',
  'The language it is written in': '使用しているプログラミング言語',
  'The engine behind every connection': 'すべての接続を支えるエンジン',
  'The Mocha and Latte palettes': 'Mocha と Latte のパレット',
  'The typeface, under the SIL Open Font License': '書体（SIL Open Font License）',
  'Copy link': 'リンクをコピー',
  'Couldn\'t open {}': '{} を開けませんでした',
  'Couldn\'t download: {}': 'ダウンロードできませんでした: {}',
  'What does this do?': 'これは何ですか？',
  'Got it': '了解',
  'Show': '表示',
  'Failed: {}.': '失敗: {}。',
  'HTTP {}': 'HTTP {}',
  'Delete {} servers?': 'サーバーを {} 件削除しますか？',
  'Donate': '寄付',
  'YouTube ads': 'YouTube 広告',
  'Blocks YouTube and Google ad requests. Ads served inside the video itself still show.': 'YouTube と Google の広告リクエストをブロックします。動画そのものに埋め込まれた広告は引き続き表示されます。',
  'Nothing is blocked.': '何もブロックしません。',
  'Blocks the well-known ad networks and trackers.': '有名な広告ネットワークとトラッカーをブロックします。',
  'Standard plus extra ads, trackers and analytics. A few apps may break.': '標準に加えて、広告・トラッカー・解析をさらにブロックします。一部のアプリが動かなくなることがあります。',
  'Renew WARP account': 'WARP アカウントを更新',
  'Create a new free account. Use this if WARP stops working.': '新しい無料アカウントを作成します。WARP が動かなくなったときに使ってください。',
  'YouTube ads: blocks the ad servers YouTube and Google use for banner, display and some video ad requests. Most video ads come from the same servers as the video itself, so a few will remain. For complete YouTube ad blocking use an ad-free client.': 'YouTube 広告：YouTube と Google がバナー、ディスプレイ、一部の動画広告のリクエストに使う広告サーバーをブロックします。動画広告の多くは動画本体と同じサーバーから配信されるため、一部は残ります。完全にブロックするには広告なしのクライアントをお使いください。',
  'Could not start the administrator helper (code {}).': '管理者ヘルパーを起動できませんでした (コード {})。',
  'Latin and Cyrillic text, under the SIL Open Font License': 'ラテン文字とキリル文字（SIL Open Font License）',
  'Persian text, under the SIL Open Font License': 'ペルシア語の文字（SIL Open Font License）',
  'Chinese text, under the SIL Open Font License': '中国語の文字（SIL Open Font License）',
  'Japanese text, under the SIL Open Font License': '日本語の文字（SIL Open Font License）',
  'DNS server': 'DNS サーバー',
  'Encrypted DNS': '暗号化 DNS',
  'Send lookups over HTTPS so nobody on the network can read them': 'HTTPS で問い合わせを送り、ネットワーク上の誰にも読まれないようにします',
  'Fake DNS': 'Fake DNS',
  'Answer lookups inside the tunnel with placeholder addresses. TUN mode only': 'トンネル内でダミーのアドレスを返して名前解決に応答します。TUN モードのみ',
  'DNS leak test': 'DNS リークテスト',
  'See which servers answer your DNS lookups': 'DNS の問い合わせにどのサーバーが応答しているか確認します',
  'Custom': 'カスタム',
  'Enter at least one DNS server': 'DNS サーバーを 1 つ以上入力してください',
  'DNS server address': 'DNS サーバーのアドレス',
  'An IP like 9.9.9.9 or an https:// DoH address, separated by commas': '9.9.9.9 のような IP、または https:// の DoH アドレス（カンマ区切り）',
  'Testing…': 'テスト中…',
  'The test failed. Check your connection.': 'テストに失敗しました。接続を確認してください。',
  'Your IP': 'あなたの IP',
  'No DNS servers were reported.': 'DNS サーバーは検出されませんでした。',
  'DNS servers that answered': '応答した DNS サーバー',
  'Run again': 'もう一度実行',
  'Update available': 'アップデートがあります',
  'Version {} is available. You have {}.': 'バージョン {} が公開されました。現在は {} です。',
  'Later': 'あとで',
  'Download': 'ダウンロード',
  'How it works: before connecting to a site, an app asks a DNS server for its address. Whoever answers can see every site you visit, and on some networks can fake the answer.': '仕組み：アプリはサイトに接続する前に、DNS サーバーにそのアドレスを尋ねます。応答する側は、あなたが訪れるすべてのサイトを見ることができ、ネットワークによっては応答を偽装することもできます。',
  'DNS server: who answers those lookups. System default uses your device\'s own DNS, which is usually your internet provider. Cloudflare, Google and Quad9 are public servers. Custom lets you enter your own.': 'DNS サーバー：この問い合わせに応答する相手です。システムのデフォルトは端末自身の DNS（通常はお使いのプロバイダー）を使います。Cloudflare、Google、Quad9 は公開サーバーです。カスタムでは独自のサーバーを入力できます。',
  'Encrypted DNS: sends the lookups over HTTPS, so the network between you and the server cannot read or change them.': '暗号化 DNS：問い合わせを HTTPS で送るため、あなたとサーバーの間のネットワークは内容を読むことも書き換えることもできません。',
  'Fake DNS: in TUN mode, answers lookups right inside the tunnel with placeholder addresses and swaps the real site name back in when the app connects. It can be faster and avoids DNS leaks, but a few apps may break.': 'Fake DNS：TUN モードで、問い合わせにトンネル内でダミーのアドレスを返し、アプリが接続するときに本当のサイト名に戻します。高速になり DNS リークも防げますが、一部のアプリが動かなくなることがあります。',
  'DNS leak test: checks which servers really answer your lookups. If you see your own provider while connected, DNS is leaking.': 'DNS リークテスト：実際にどのサーバーが問い合わせに応答しているか確認します。接続中に自分のプロバイダーが表示される場合、DNS が漏れています。',
};
