const Map<String, String> stringsId = {
  'Home': 'Beranda',
  'Servers': 'Server',
  'Routing': 'Perutean',
  'Settings': 'Pengaturan',
  'About': 'Tentang',
  'Disconnected': 'Terputus',
  'Tap to connect': 'Ketuk untuk terhubung',
  'Connecting': 'Menghubungkan',
  'Connecting…': 'Menghubungkan…',
  'Starting the tunnel': 'Memulai terowongan',
  'Connected': 'Terhubung',
  'Connect': 'Hubungkan',
  'Disconnect': 'Putuskan',
  'Quit': 'Keluar',
  'Show {}': 'Tampilkan {}',
  '{} is connected': '{} terhubung',
  '{} is disconnected': '{} terputus',
  'Your traffic is routed through the proxy.': 'Lalu lintas Anda dialihkan melalui proxy.',
  'Your traffic is going directly.': 'Lalu lintas Anda berjalan langsung.',
  'Proxy': 'Proxy',
  'TUN': 'TUN',
  'Down': 'Unduh',
  'Up': 'Unggah',
  'Ping': 'Ping',
  'Mixed': 'Campuran',
  'Copy address': 'Salin alamat',
  'Copied {}': '{} disalin',
  'Test latency': 'Uji latensi',
  'Free configs': 'Konfigurasi gratis',
  'Share all servers': 'Bagikan semua server',
  'Add server': 'Tambah server',
  'Sort servers': 'Urutkan server',
  'Oldest first': 'Terlama dulu',
  'Newest first': 'Terbaru dulu',
  'Lowest ping': 'Ping terendah',
  'Name': 'Nama',
  'Protocol': 'Protokol',
  'No servers yet. Tap + to add one.': 'Belum ada server. Ketuk + untuk menambah.',
  'Delete server?': 'Hapus server?',
  'Cancel': 'Batal',
  'Delete': 'Hapus',
  'Clipboard is empty': 'Papan klip kosong',
  'No share links found in the clipboard': 'Tidak ada tautan berbagi di papan klip',
  'Added 1 server': '1 server ditambahkan',
  'Added {} servers': '{} server ditambahkan',
  'Added {} server(s), {} line(s) had errors': '{} server ditambahkan, {} baris bermasalah',
  'No servers found': 'Server tidak ditemukan',
  'Password': 'Kata sandi',
  'File password': 'Kata sandi berkas',
  'Open': 'Buka',
  'Subscription URL': 'URL langganan',
  'Import': 'Impor',
  'Paste from clipboard': 'Tempel dari papan klip',
  'One or more vless, vmess, trojan or ss links': 'Satu atau lebih tautan vless, vmess, trojan atau ss',
  'Download a whole list of servers': 'Unduh seluruh daftar server',
  'Import .pray file': 'Impor berkas .pray',
  'Servers shared by another Pray app': 'Server yang dibagikan dari aplikasi Pray lain',
  'Scan QR code': 'Pindai kode QR',
  'Use the camera': 'Gunakan kamera',
  'QR scanning': 'Pemindaian QR',
  '{} arrives with the Xray core.': '{} hadir bersama inti Xray.',
  'Enter a valid address and port (1-65535).': 'Masukkan alamat dan port yang valid (1-65535).',
  'Edit server': 'Ubah server',
  'Address': 'Alamat',
  'Port': 'Port',
  'UUID': 'UUID',
  'Save': 'Simpan',
  'Add': 'Tambah',
  'Remove': 'Hapus',
  'Done': 'Selesai',
  'Close': 'Tutup',
  'Copy': 'Salin',
  'Link': 'Tautan',
  'File': 'Berkas',
  'Search': 'Cari',
  'More': 'Lainnya',
  'Share': 'Bagikan',
  'Edit': 'Ubah',
  'Pin to top': 'Sematkan di atas',
  'Unpin': 'Lepas sematan',
  'Enter a password or turn protection off.': 'Masukkan kata sandi atau matikan perlindungan.',
  'Saved {}': '{} disimpan',
  'Save {}': 'Simpan {}',
  'Link copied': 'Tautan disalin',
  'Links copied': 'Tautan disalin',
  'Protect with a password': 'Lindungi dengan kata sandi',
  'Only people with the password can open it': 'Hanya orang yang punya kata sandi yang bisa membukanya',
  'Any Pray app can open it': 'Aplikasi Pray mana pun dapat membukanya',
  'Too long for a QR code': 'Terlalu panjang untuk kode QR',
  'Where traffic goes': 'Ke mana lalu lintas pergi',
  'Proxy everything': 'Proxy semuanya',
  'Bypass local network': 'Lewati jaringan lokal',
  'Bypass Iran': 'Lewati Iran',
  'All traffic goes through the server': 'Semua lalu lintas melalui server',
  'Local addresses connect directly': 'Alamat lokal terhubung langsung',
  'Iranian sites and IPs connect directly': 'Situs dan IP Iran terhubung langsung',
  ' — disconnect to change': ' — putuskan untuk mengubah',
  'Proxy everything: all traffic goes through the server.': 'Proxy semuanya: semua lalu lintas melalui server.',
  'Bypass local network: only addresses on your own network (router, printers, other devices) connect directly. Everything else goes through the server.': 'Lewati jaringan lokal: hanya alamat di jaringan Anda sendiri (router, printer, perangkat lain) yang terhubung langsung. Sisanya melalui server.',
  'Bypass Iran: Iranian sites (.ir and known Iranian domains) and Iranian IP addresses connect directly, as well as your local network. Everything else goes through the server.': 'Lewati Iran: situs Iran (.ir dan domain Iran yang dikenal), alamat IP Iran, serta jaringan lokal Anda terhubung langsung. Sisanya melalui server.',
  'Ad blocking': 'Pemblokir iklan',
  'Off': 'Mati',
  'Standard': 'Standar',
  'Strict': 'Ketat',
  'How it works: while connected, Pray looks at the name of every site or server an app tries to reach and drops the connection if the name is on a block list. Nothing is installed on your device and no traffic is read.': 'Cara kerja: saat terhubung, Pray memeriksa nama setiap situs atau server yang dituju aplikasi dan memutus koneksi jika namanya ada di daftar blokir. Tidak ada yang dipasang di perangkat Anda dan lalu lintas tidak dibaca.',
  'Off: nothing is blocked.': 'Mati: tidak ada yang diblokir.',
  'Standard: blocks the well-known ad networks and trackers from the built-in geo data.': 'Standar: memblokir jaringan iklan dan pelacak terkenal dari data geo bawaan.',
  'Strict: Standard plus extra ad, tracker and analytics domains built into Pray, including Iranian ad networks. A few apps may stop working.': 'Ketat: Standar ditambah domain iklan, pelacak, dan analitik lain yang tertanam di Pray, termasuk jaringan iklan Iran. Beberapa aplikasi mungkin berhenti berfungsi.',
  'Filter lists: download community lists such as StevenBlack, HaGeZi or PersianBlocker for much wider coverage, or add your own list URL. You can also block single sites in Custom rules below.': 'Daftar filter: unduh daftar komunitas seperti StevenBlack, HaGeZi, atau PersianBlocker untuk cakupan jauh lebih luas, atau tambahkan URL daftar Anda sendiri. Anda juga bisa memblokir situs tertentu di Aturan khusus di bawah.',
  'Limits: ads served from the same address as the content (most YouTube and in-app video ads) cannot be told apart and still show. Encrypted DNS inside an app can also bypass name-based blocking.': 'Batasan: iklan yang disajikan dari alamat yang sama dengan kontennya (sebagian besar iklan YouTube dan iklan video dalam aplikasi) tidak bisa dibedakan dan tetap tampil. DNS terenkripsi di dalam aplikasi juga dapat melewati pemblokiran berbasis nama.',
  'Filter lists': 'Daftar filter',
  '{} enabled': '{} aktif',
  'Add filter list': 'Tambah daftar filter',
  'List URL': 'URL daftar',
  'Hosts, plain domain or AdGuard-style list': 'Hosts, domain biasa, atau daftar gaya AdGuard',
  'Turn on the lists you want, then download them. Every domain in an enabled list is blocked while Pray is connected. More lists block more, but can break some sites and apps.': 'Aktifkan daftar yang Anda inginkan, lalu unduh. Setiap domain dalam daftar aktif diblokir saat Pray terhubung. Semakin banyak daftar, semakin banyak yang diblokir, tetapi beberapa situs dan aplikasi bisa rusak.',
  'Add a list': 'Tambah daftar',
  'Download enabled lists': 'Unduh daftar yang aktif',
  'Downloading…': 'Mengunduh…',
  'Downloading {}%': 'Mengunduh {}%',
  '{} domains': '{} domain',
  '{} domains, updated {}': '{} domain, diperbarui {}',
  '{} domains ready.': '{} domain siap.',
  'Reconnect after updating to apply the new lists.': 'Hubungkan ulang setelah memperbarui untuk menerapkan daftar baru.',
  'Apps': 'Aplikasi',
  'Per-app proxy': 'Proxy per aplikasi',
  'Choose which apps use the VPN': 'Pilih aplikasi yang memakai VPN',
  'Choose apps': 'Pilih aplikasi',
  '{} selected': '{} dipilih',
  'Apps ({})': 'Aplikasi ({})',
  'Custom rules': 'Aturan khusus',
  'Through the proxy': 'Melalui proxy',
  'Direct': 'Langsung',
  'Block': 'Blokir',
  'Blocked': 'Diblokir',
  'Remove rule': 'Hapus aturan',
  'Add a rule': 'Tambah aturan',
  'Add another rule': 'Tambah aturan lain',
  'Send a domain or IP through the proxy, direct, or block it': 'Kirim domain atau IP melalui proxy, langsung, atau blokir',
  'Enter a domain, IP or CIDR': 'Masukkan domain, IP, atau CIDR',
  'Add rule': 'Tambah aturan',
  'Domain, IP or CIDR': 'Domain, IP, atau CIDR',
  'Cloudflare WARP': 'Cloudflare WARP',
  'WARP only': 'Hanya WARP',
  'Server, then WARP': 'Server, lalu WARP',
  'WARP for chosen sites': 'WARP untuk situs tertentu',
  'Use only your server': 'Gunakan server Anda saja',
  'Send everything through Cloudflare WARP, no server needed': 'Kirim semuanya melalui Cloudflare WARP, tanpa server',
  'Your server first, then Cloudflare, so sites see a Cloudflare address': 'Server Anda dulu, lalu Cloudflare, sehingga situs melihat alamat Cloudflare',
  'Normal routing, but the sites you list leave through WARP': 'Perutean normal, tetapi situs yang Anda daftarkan keluar melalui WARP',
  'WARP endpoint': 'Endpoint WARP',
  'Default {}': 'Bawaan {}',
  'Sites that use WARP': 'Situs yang memakai WARP',
  'One per line, like openai.com or geosite:netflix': 'Satu per baris, misalnya openai.com atau geosite:netflix',
  '{} entries': '{} entri',
  'Endpoint': 'Endpoint',
  'WARP is a free Cloudflare tunnel. Pray can create a free WARP account for you and use it in three ways.': 'WARP adalah terowongan Cloudflare gratis. Pray dapat membuatkan akun WARP gratis dan memakainya dengan tiga cara.',
  'WARP only: all traffic goes straight through Cloudflare. No server is needed, but WARP is blocked on some networks.': 'Hanya WARP: semua lalu lintas langsung melalui Cloudflare. Tidak perlu server, tetapi WARP diblokir di beberapa jaringan.',
  'Server, then WARP: traffic goes through your server first and leaves from a Cloudflare address. This helps with sites that block server addresses, and hides your server address from those sites.': 'Server, lalu WARP: lalu lintas melewati server Anda lebih dulu dan keluar dari alamat Cloudflare. Ini membantu untuk situs yang memblokir alamat server, dan menyembunyikan alamat server Anda dari situs tersebut.',
  'WARP for chosen sites: everything uses your normal route, but the sites you list (for example AI services) go through WARP.': 'WARP untuk situs tertentu: semuanya memakai rute normal, tetapi situs yang Anda daftarkan (misalnya layanan AI) melewati WARP.',
  'WARP hides your address from sites, it does not hide your traffic from Cloudflare.': 'WARP menyembunyikan alamat Anda dari situs, tetapi tidak menyembunyikan lalu lintas Anda dari Cloudflare.',
  'No WARP account': 'Tidak ada akun WARP',
  'WARP account ready': 'Akun WARP siap',
  'Tap to create a free account': 'Ketuk untuk membuat akun gratis',
  'Tap the bin to remove it': 'Ketuk tempat sampah untuk menghapus',
  'Remove account': 'Hapus akun',
  'Register a WARP account first (Routing, WARP).': 'Daftarkan akun WARP terlebih dahulu (Perutean, WARP).',
  'Add a server first.': 'Tambahkan server terlebih dahulu.',
  'Per-app proxy is on, but no apps are selected.': 'Proxy per aplikasi aktif, tetapi tidak ada aplikasi yang dipilih.',
  'VPN permission was not granted.': 'Izin VPN tidak diberikan.',
  'The VPN was turned off by Android.': 'VPN dimatikan oleh Android.',
  'xray stopped unexpectedly. Check the log for details.': 'xray berhenti tiba-tiba. Periksa log untuk detailnya.',
  'Administrator permission was not granted.': 'Izin administrator tidak diberikan.',
  'xray did not create the TUN interface.': 'xray tidak membuat antarmuka TUN.',
  'xray is already running.': 'xray sudah berjalan.',
  'No bundled xray for this platform.': 'Tidak ada xray bawaan untuk platform ini.',
  'No geo data folder.': 'Tidak ada folder data geo.',
  'Download failed': 'Unduhan gagal',
  'Downloaded file is too small': 'Berkas yang diunduh terlalu kecil',
  'The file is too large': 'Berkas terlalu besar',
  'This is not a .pray file.': 'Ini bukan berkas .pray.',
  'This .pray file is from a newer version.': 'Berkas .pray ini berasal dari versi yang lebih baru.',
  'A password is required.': 'Kata sandi diperlukan.',
  'Wrong password or damaged file.': 'Kata sandi salah atau berkas rusak.',
  'The file is damaged.': 'Berkas rusak.',
  'The file content is not valid.': 'Isi berkas tidak valid.',
  'WARP registration timed out': 'Pendaftaran WARP kehabisan waktu',
  'WARP registration failed (HTTP {})': 'Pendaftaran WARP gagal (HTTP {})',
  'Install zenity or kdialog to choose files.': 'Pasang zenity atau kdialog untuk memilih berkas.',
  'Add source': 'Tambah sumber',
  'Looking for servers…': 'Mencari server…',
  'Nothing could be downloaded. Check your internet connection and try again.': 'Tidak ada yang bisa diunduh. Periksa koneksi internet dan coba lagi.',
  'Checking which ones work…': 'Memeriksa mana yang berfungsi…',
  'No working server was found right now. Try again later.': 'Tidak ada server yang berfungsi saat ini. Coba lagi nanti.',
  'Added {} server(s)': '{} server ditambahkan',
  'Sources': 'Sumber',
  'Choose servers': 'Pilih server',
  'Free servers': 'Server gratis',
  'Find free servers': 'Cari server gratis',
  'Pray looks for free servers shared by volunteers, checks which ones work and adds the fastest ones for you.': 'Pray mencari server gratis yang dibagikan relawan, memeriksa mana yang berfungsi, dan menambahkan yang tercepat untuk Anda.',
  'Change where to look': 'Ubah sumber pencarian',
  'Free servers are shared with many people. Do not use them for banking or private accounts.': 'Server gratis dipakai banyak orang. Jangan gunakan untuk perbankan atau akun pribadi.',
  'Add a source': 'Tambah sumber',
  'Restore the default sources': 'Pulihkan sumber bawaan',
  'This can take a minute.': 'Ini bisa memakan waktu semenit.',
  '{} working servers found': '{} server berfungsi ditemukan',
  'Add the best {}': 'Tambah {} terbaik',
  'Let me choose': 'Biar saya pilih',
  '{} of {} selected': '{} dari {} dipilih',
  'Select all': 'Pilih semua',
  'Deselect all': 'Batalkan semua',
  'Tip: press and hold a row, then drag to select many.': 'Tips: tekan dan tahan satu baris, lalu seret untuk memilih banyak.',
  'Add {}': 'Tambah {}',
  'Appearance': 'Tampilan',
  'Auto': 'Otomatis',
  'Latte': 'Latte',
  'Mocha': 'Mocha',
  'Language': 'Bahasa',
  'System default': 'Bawaan sistem',
  'Network': 'Jaringan',
  'Proxy port': 'Port proxy',
  'SOCKS5 proxy, also available while TUN is on': 'Proxy SOCKS5, juga tersedia saat TUN aktif',
  'Allow LAN connections': 'Izinkan koneksi LAN',
  'Let other devices use the proxy': 'Biarkan perangkat lain memakai proxy',
  'Startup': 'Mulai',
  'Connect on launch': 'Hubungkan saat dibuka',
  'Start the tunnel when Pray opens': 'Mulai terowongan saat Pray dibuka',
  'Launch at login': 'Jalankan saat masuk',
  'Start Pray with your session': 'Mulai Pray bersama sesi Anda',
  'Core': 'Inti',
  'Geo data': 'Data geo',
  'Download the latest geoip and geosite': 'Unduh geoip dan geosite terbaru',
  'Last updated {}': 'Terakhir diperbarui {}',
  'Geo data updated. Reconnect to use it.': 'Data geo diperbarui. Hubungkan ulang untuk memakainya.',
  'Enter a port from {} to {}': 'Masukkan port dari {} sampai {}',
  'Version {}': 'Versi {}',
  'Made with love by {}': 'Dibuat dengan cinta oleh {}',
  'Links': 'Tautan',
  'Built with': 'Dibangun dengan',
  'The toolkit behind the interface': 'Perangkat di balik antarmuka',
  'The language it is written in': 'Bahasa pemrograman yang dipakai',
  'The engine behind every connection': 'Mesin di balik setiap koneksi',
  'The Mocha and Latte palettes': 'Palet Mocha dan Latte',
  'The typeface, under the SIL Open Font License': 'Jenis huruf, berlisensi SIL Open Font License',
  'Copy link': 'Salin tautan',
  'Couldn\'t open {}': 'Tidak bisa membuka {}',
  'Couldn\'t download: {}': 'Tidak bisa mengunduh: {}',
  'What does this do?': 'Apa fungsinya?',
  'Got it': 'Mengerti',
  'Show': 'Tampilkan',
  'Failed: {}.': 'Gagal: {}.',
  'HTTP {}': 'HTTP {}',
  'Delete {} servers?': 'Hapus {} server?',
  'Donate': 'Donasi',
  'YouTube ads': 'Iklan YouTube',
  'Blocks YouTube and Google ad requests. Ads served inside the video itself still show.': 'Memblokir permintaan iklan YouTube dan Google. Iklan yang disajikan di dalam video itu sendiri tetap tampil.',
  'Nothing is blocked.': 'Tidak ada yang diblokir.',
  'Blocks the well-known ad networks and trackers.': 'Memblokir jaringan iklan dan pelacak terkenal.',
  'Standard plus extra ads, trackers and analytics. A few apps may break.': 'Standar ditambah lebih banyak iklan, pelacak, dan analitik. Beberapa aplikasi mungkin rusak.',
  'Renew WARP account': 'Perbarui akun WARP',
  'Create a new free account. Use this if WARP stops working.': 'Buat akun gratis baru. Gunakan jika WARP berhenti berfungsi.',
  'YouTube ads: blocks the ad servers YouTube and Google use for banner, display and some video ad requests. Most video ads come from the same servers as the video itself, so a few will remain. For complete YouTube ad blocking use an ad-free client.': 'Iklan YouTube: memblokir server iklan yang dipakai YouTube dan Google untuk banner, iklan tampilan, dan sebagian permintaan iklan video. Sebagian besar iklan video berasal dari server yang sama dengan videonya, jadi sebagian akan tetap muncul. Untuk pemblokiran penuh gunakan klien tanpa iklan.',
  'Could not start the administrator helper (code {}).': 'Tidak bisa memulai pembantu administrator (kode {}).',
  'Latin and Cyrillic text, under the SIL Open Font License': 'Teks Latin dan Kiril, berlisensi SIL Open Font License',
  'Persian text, under the SIL Open Font License': 'Teks Persia, berlisensi SIL Open Font License',
  'Chinese text, under the SIL Open Font License': 'Teks Tionghoa, berlisensi SIL Open Font License',
  'Japanese text, under the SIL Open Font License': 'Teks Jepang, berlisensi SIL Open Font License',
  'DNS server': 'Server DNS',
  'Encrypted DNS': 'DNS terenkripsi',
  'Send lookups over HTTPS so nobody on the network can read them': 'Kirim kueri lewat HTTPS agar tidak ada yang di jaringan bisa membacanya',
  'Fake DNS': 'Fake DNS',
  'Answer lookups inside the tunnel with placeholder addresses. TUN mode only': 'Jawab kueri di dalam terowongan dengan alamat pengganti. Hanya mode TUN',
  'DNS leak test': 'Tes kebocoran DNS',
  'See which servers answer your DNS lookups': 'Lihat server mana yang menjawab kueri DNS Anda',
  'Custom': 'Kustom',
  'Enter at least one DNS server': 'Masukkan minimal satu server DNS',
  'DNS server address': 'Alamat server DNS',
  'An IP like 9.9.9.9 or an https:// DoH address, separated by commas': 'IP seperti 9.9.9.9 atau alamat DoH https://, dipisahkan koma',
  'Testing…': 'Menguji…',
  'The test failed. Check your connection.': 'Tes gagal. Periksa koneksi Anda.',
  'Your IP': 'IP Anda',
  'No DNS servers were reported.': 'Tidak ada server DNS yang terdeteksi.',
  'DNS servers that answered': 'Server DNS yang menjawab',
  'Run again': 'Jalankan lagi',
  'Update available': 'Pembaruan tersedia',
  'Version {} is available. You have {}.': 'Versi {} tersedia. Anda memakai {}.',
  'Later': 'Nanti',
  'Download': 'Unduh',
  'How it works: before connecting to a site, an app asks a DNS server for its address. Whoever answers can see every site you visit, and on some networks can fake the answer.': 'Cara kerja: sebelum terhubung ke sebuah situs, aplikasi menanyakan alamatnya ke server DNS. Yang menjawab bisa melihat setiap situs yang Anda kunjungi, dan di beberapa jaringan bisa memalsukan jawabannya.',
  'DNS server: who answers those lookups. System default uses your device\'s own DNS, which is usually your internet provider. Cloudflare, Google and Quad9 are public servers. Custom lets you enter your own.': 'Server DNS: siapa yang menjawab kueri itu. Bawaan sistem memakai DNS perangkat Anda sendiri, biasanya penyedia internet Anda. Cloudflare, Google, dan Quad9 adalah server publik. Kustom memungkinkan Anda memasukkan server sendiri.',
  'Encrypted DNS: sends the lookups over HTTPS, so the network between you and the server cannot read or change them.': 'DNS terenkripsi: mengirim kueri lewat HTTPS, sehingga jaringan di antara Anda dan server tidak bisa membaca atau mengubahnya.',
  'Fake DNS: in TUN mode, answers lookups right inside the tunnel with placeholder addresses and swaps the real site name back in when the app connects. It can be faster and avoids DNS leaks, but a few apps may break.': 'Fake DNS: pada mode TUN, menjawab kueri langsung di dalam terowongan dengan alamat pengganti dan mengembalikan nama situs asli saat aplikasi terhubung. Bisa lebih cepat dan mencegah kebocoran DNS, tetapi beberapa aplikasi mungkin rusak.',
  'DNS leak test: checks which servers really answer your lookups. If you see your own provider while connected, DNS is leaking.': 'Tes kebocoran DNS: memeriksa server mana yang benar-benar menjawab kueri Anda. Jika Anda melihat penyedia sendiri saat terhubung, berarti DNS bocor.',
};
