const Map<String, String> stringsRu = {
  'Home': 'Главная',
  'Servers': 'Серверы',
  'Routing': 'Маршрутизация',
  'Settings': 'Настройки',
  'About': 'О приложении',
  'Disconnected': 'Отключено',
  'Tap to connect': 'Нажмите для подключения',
  'Connecting': 'Подключение',
  'Connecting…': 'Подключение…',
  'Starting the tunnel': 'Запуск туннеля',
  'Connected': 'Подключено',
  'Connect': 'Подключить',
  'Disconnect': 'Отключить',
  'Quit': 'Выход',
  'Show {}': 'Показать {}',
  '{} is connected': '{} подключён',
  '{} is disconnected': '{} отключён',
  'Your traffic is routed through the proxy.': 'Ваш трафик идёт через прокси.',
  'Your traffic is going directly.': 'Ваш трафик идёт напрямую.',
  'Proxy': 'Прокси',
  'TUN': 'TUN',
  'Down': 'Загрузка',
  'Up': 'Отдача',
  'Ping': 'Пинг',
  'Mixed': 'Смешанный',
  'Copy address': 'Копировать адрес',
  'Copied {}': 'Скопировано: {}',
  'Test latency': 'Проверить задержку',
  'Free configs': 'Бесплатные конфиги',
  'Share all servers': 'Поделиться всеми серверами',
  'Add server': 'Добавить сервер',
  'Sort servers': 'Сортировка серверов',
  'Oldest first': 'Сначала старые',
  'Newest first': 'Сначала новые',
  'Lowest ping': 'Наименьший пинг',
  'Name': 'Имя',
  'Protocol': 'Протокол',
  'No servers yet. Tap + to add one.': 'Серверов пока нет. Нажмите +, чтобы добавить.',
  'Delete server?': 'Удалить сервер?',
  'Cancel': 'Отмена',
  'Delete': 'Удалить',
  'Clipboard is empty': 'Буфер обмена пуст',
  'No share links found in the clipboard': 'В буфере обмена нет ссылок',
  'Added 1 server': 'Добавлен 1 сервер',
  'Added {} servers': 'Добавлено серверов: {}',
  'Added {} server(s), {} line(s) had errors': 'Добавлено серверов: {}, строк с ошибками: {}',
  'No servers found': 'Серверы не найдены',
  'Password': 'Пароль',
  'File password': 'Пароль файла',
  'Open': 'Открыть',
  'Subscription URL': 'URL подписки',
  'Import': 'Импорт',
  'Paste from clipboard': 'Вставить из буфера',
  'One or more vless, vmess, trojan or ss links': 'Одна или несколько ссылок vless, vmess, trojan или ss',
  'Download a whole list of servers': 'Загрузить целый список серверов',
  'Import .pray file': 'Импорт файла .pray',
  'Servers shared by another Pray app': 'Серверы, которыми поделились из другого Pray',
  'Scan QR code': 'Сканировать QR-код',
  'Use the camera': 'Использовать камеру',
  'QR scanning': 'Сканирование QR',
  '{} arrives with the Xray core.': '{} появится вместе с ядром Xray.',
  'Enter a valid address and port (1-65535).': 'Введите корректные адрес и порт (1–65535).',
  'Edit server': 'Изменить сервер',
  'Address': 'Адрес',
  'Port': 'Порт',
  'UUID': 'UUID',
  'Save': 'Сохранить',
  'Add': 'Добавить',
  'Remove': 'Убрать',
  'Done': 'Готово',
  'Close': 'Закрыть',
  'Copy': 'Копировать',
  'Link': 'Ссылка',
  'File': 'Файл',
  'Search': 'Поиск',
  'More': 'Ещё',
  'Share': 'Поделиться',
  'Edit': 'Изменить',
  'Pin to top': 'Закрепить сверху',
  'Unpin': 'Открепить',
  'Enter a password or turn protection off.': 'Введите пароль или отключите защиту.',
  'Saved {}': 'Сохранено: {}',
  'Save {}': 'Сохранить {}',
  'Link copied': 'Ссылка скопирована',
  'Links copied': 'Ссылки скопированы',
  'Protect with a password': 'Защитить паролем',
  'Only people with the password can open it': 'Открыть смогут только те, кто знает пароль',
  'Any Pray app can open it': 'Его откроет любое приложение Pray',
  'Too long for a QR code': 'Слишком длинно для QR-кода',
  'Where traffic goes': 'Куда идёт трафик',
  'Proxy everything': 'Всё через прокси',
  'Bypass local network': 'Напрямую в локальную сеть',
  'Bypass Iran': 'Напрямую в Иран',
  'All traffic goes through the server': 'Весь трафик идёт через сервер',
  'Local addresses connect directly': 'Локальные адреса подключаются напрямую',
  'Iranian sites and IPs connect directly': 'Иранские сайты и IP подключаются напрямую',
  ' — disconnect to change': ' — отключитесь, чтобы изменить',
  'Proxy everything: all traffic goes through the server.': 'Всё через прокси: весь трафик идёт через сервер.',
  'Bypass local network: only addresses on your own network (router, printers, other devices) connect directly. Everything else goes through the server.': 'Напрямую в локальную сеть: только адреса вашей сети (роутер, принтеры, другие устройства) подключаются напрямую. Всё остальное идёт через сервер.',
  'Bypass Iran: Iranian sites (.ir and known Iranian domains) and Iranian IP addresses connect directly, as well as your local network. Everything else goes through the server.': 'Напрямую в Иран: иранские сайты (.ir и известные иранские домены), иранские IP-адреса и ваша локальная сеть подключаются напрямую. Всё остальное идёт через сервер.',
  'Ad blocking': 'Блокировка рекламы',
  'Off': 'Выкл.',
  'Standard': 'Стандартный',
  'Strict': 'Строгий',
  'How it works: while connected, Pray looks at the name of every site or server an app tries to reach and drops the connection if the name is on a block list. Nothing is installed on your device and no traffic is read.': 'Как это работает: пока есть подключение, Pray смотрит на имя каждого сайта или сервера, к которому обращается приложение, и обрывает соединение, если имя есть в списке блокировки. Ничего не устанавливается на устройство, трафик не читается.',
  'Off: nothing is blocked.': 'Выкл.: ничего не блокируется.',
  'Standard: blocks the well-known ad networks and trackers from the built-in geo data.': 'Стандартный: блокирует известные рекламные сети и трекеры из встроенных гео-данных.',
  'Strict: Standard plus extra ad, tracker and analytics domains built into Pray, including Iranian ad networks. A few apps may stop working.': 'Строгий: Стандартный плюс дополнительные рекламные, трекерные и аналитические домены, встроенные в Pray, включая иранские рекламные сети. Некоторые приложения могут перестать работать.',
  'Filter lists: download community lists such as StevenBlack, HaGeZi or PersianBlocker for much wider coverage, or add your own list URL. You can also block single sites in Custom rules below.': 'Списки фильтров: скачайте списки сообщества, такие как StevenBlack, HaGeZi или PersianBlocker, для гораздо более широкого охвата или добавьте URL своего списка. Отдельные сайты можно заблокировать в разделе «Свои правила» ниже.',
  'Limits: ads served from the same address as the content (most YouTube and in-app video ads) cannot be told apart and still show. Encrypted DNS inside an app can also bypass name-based blocking.': 'Ограничения: реклама, которая приходит с того же адреса, что и контент (большая часть рекламы YouTube и видеорекламы в приложениях), неотличима и всё равно показывается. Зашифрованный DNS внутри приложения тоже может обойти блокировку по имени.',
  'Filter lists': 'Списки фильтров',
  '{} enabled': 'Включено: {}',
  'Add filter list': 'Добавить список фильтров',
  'List URL': 'URL списка',
  'Hosts, plain domain or AdGuard-style list': 'Hosts, список доменов или список в стиле AdGuard',
  'Turn on the lists you want, then download them. Every domain in an enabled list is blocked while Pray is connected. More lists block more, but can break some sites and apps.': 'Включите нужные списки и скачайте их. Каждый домен из включённых списков блокируется, пока Pray подключён. Больше списков — больше блокировок, но некоторые сайты и приложения могут сломаться.',
  'Add a list': 'Добавить список',
  'Download enabled lists': 'Скачать включённые списки',
  'Downloading…': 'Загрузка…',
  'Downloading {}%': 'Загрузка {}%',
  '{} domains': 'Доменов: {}',
  '{} domains, updated {}': 'Доменов: {}, обновлено {}',
  '{} domains ready.': 'Доменов готово: {}.',
  'Reconnect after updating to apply the new lists.': 'Переподключитесь после обновления, чтобы применить новые списки.',
  'Apps': 'Приложения',
  'Per-app proxy': 'Прокси для приложений',
  'Choose which apps use the VPN': 'Выберите приложения, использующие VPN',
  'Choose apps': 'Выбрать приложения',
  '{} selected': 'Выбрано: {}',
  'Apps ({})': 'Приложения ({})',
  'Custom rules': 'Свои правила',
  'Through the proxy': 'Через прокси',
  'Direct': 'Напрямую',
  'Block': 'Блок',
  'Blocked': 'Блокировка',
  'Remove rule': 'Удалить правило',
  'Add a rule': 'Добавить правило',
  'Add another rule': 'Добавить ещё правило',
  'Send a domain or IP through the proxy, direct, or block it': 'Отправьте домен или IP через прокси, напрямую или заблокируйте его',
  'Enter a domain, IP or CIDR': 'Введите домен, IP или CIDR',
  'Add rule': 'Добавить правило',
  'Domain, IP or CIDR': 'Домен, IP или CIDR',
  'Cloudflare WARP': 'Cloudflare WARP',
  'WARP only': 'Только WARP',
  'Server, then WARP': 'Сервер, затем WARP',
  'WARP for chosen sites': 'WARP для выбранных сайтов',
  'Use only your server': 'Использовать только свой сервер',
  'Send everything through Cloudflare WARP, no server needed': 'Всё через Cloudflare WARP, сервер не нужен',
  'Your server first, then Cloudflare, so sites see a Cloudflare address': 'Сначала ваш сервер, затем Cloudflare — сайты видят адрес Cloudflare',
  'Normal routing, but the sites you list leave through WARP': 'Обычная маршрутизация, но перечисленные сайты идут через WARP',
  'WARP endpoint': 'Адрес WARP',
  'Default {}': 'По умолчанию {}',
  'Sites that use WARP': 'Сайты через WARP',
  'One per line, like openai.com or geosite:netflix': 'По одному в строке, например openai.com или geosite:netflix',
  '{} entries': 'Записей: {}',
  'Endpoint': 'Адрес',
  'WARP is a free Cloudflare tunnel. Pray can create a free WARP account for you and use it in three ways.': 'WARP — это бесплатный туннель Cloudflare. Pray может создать для вас бесплатный аккаунт WARP и использовать его тремя способами.',
  'WARP only: all traffic goes straight through Cloudflare. No server is needed, but WARP is blocked on some networks.': 'Только WARP: весь трафик идёт напрямую через Cloudflare. Сервер не нужен, но в некоторых сетях WARP заблокирован.',
  'Server, then WARP: traffic goes through your server first and leaves from a Cloudflare address. This helps with sites that block server addresses, and hides your server address from those sites.': 'Сервер, затем WARP: трафик сначала идёт через ваш сервер, а выходит с адреса Cloudflare. Это помогает с сайтами, блокирующими адреса серверов, и скрывает адрес вашего сервера от них.',
  'WARP for chosen sites: everything uses your normal route, but the sites you list (for example AI services) go through WARP.': 'WARP для выбранных сайтов: всё идёт обычным маршрутом, а перечисленные сайты (например, ИИ-сервисы) — через WARP.',
  'WARP hides your address from sites, it does not hide your traffic from Cloudflare.': 'WARP скрывает ваш адрес от сайтов, но не скрывает трафик от Cloudflare.',
  'No WARP account': 'Нет аккаунта WARP',
  'WARP account ready': 'Аккаунт WARP готов',
  'Tap to create a free account': 'Нажмите, чтобы создать бесплатный аккаунт',
  'Tap the bin to remove it': 'Нажмите на корзину, чтобы удалить',
  'Remove account': 'Удалить аккаунт',
  'Register a WARP account first (Routing, WARP).': 'Сначала создайте аккаунт WARP (Маршрутизация, WARP).',
  'Add a server first.': 'Сначала добавьте сервер.',
  'Per-app proxy is on, but no apps are selected.': 'Прокси для приложений включён, но приложения не выбраны.',
  'VPN permission was not granted.': 'Разрешение на VPN не предоставлено.',
  'The VPN was turned off by Android.': 'VPN был отключён Android.',
  'xray stopped unexpectedly. Check the log for details.': 'xray неожиданно остановился. Подробности в журнале.',
  'Administrator permission was not granted.': 'Права администратора не предоставлены.',
  'xray did not create the TUN interface.': 'xray не создал интерфейс TUN.',
  'xray is already running.': 'xray уже запущен.',
  'No bundled xray for this platform.': 'Для этой платформы нет встроенного xray.',
  'No geo data folder.': 'Нет папки гео-данных.',
  'Download failed': 'Не удалось скачать',
  'Downloaded file is too small': 'Скачанный файл слишком мал',
  'The file is too large': 'Файл слишком большой',
  'This is not a .pray file.': 'Это не файл .pray.',
  'This .pray file is from a newer version.': 'Этот файл .pray создан в более новой версии.',
  'A password is required.': 'Требуется пароль.',
  'Wrong password or damaged file.': 'Неверный пароль или повреждённый файл.',
  'The file is damaged.': 'Файл повреждён.',
  'The file content is not valid.': 'Содержимое файла недопустимо.',
  'WARP registration timed out': 'Время регистрации WARP истекло',
  'WARP registration failed (HTTP {})': 'Не удалось зарегистрировать WARP (HTTP {})',
  'Install zenity or kdialog to choose files.': 'Установите zenity или kdialog для выбора файлов.',
  'Add source': 'Добавить источник',
  'Looking for servers…': 'Поиск серверов…',
  'Nothing could be downloaded. Check your internet connection and try again.': 'Ничего не удалось скачать. Проверьте интернет и попробуйте снова.',
  'Checking which ones work…': 'Проверяем, какие работают…',
  'No working server was found right now. Try again later.': 'Сейчас рабочих серверов не найдено. Попробуйте позже.',
  'Added {} server(s)': 'Добавлено серверов: {}',
  'Sources': 'Источники',
  'Choose servers': 'Выбор серверов',
  'Free servers': 'Бесплатные серверы',
  'Find free servers': 'Найти бесплатные серверы',
  'Pray looks for free servers shared by volunteers, checks which ones work and adds the fastest ones for you.': 'Pray ищет бесплатные серверы, которыми делятся волонтёры, проверяет, какие работают, и добавляет самые быстрые.',
  'Change where to look': 'Изменить источники',
  'Free servers are shared with many people. Do not use them for banking or private accounts.': 'Бесплатными серверами пользуются многие. Не используйте их для банков и личных аккаунтов.',
  'Add a source': 'Добавить источник',
  'Restore the default sources': 'Восстановить источники по умолчанию',
  'This can take a minute.': 'Это может занять минуту.',
  '{} working servers found': 'Найдено рабочих серверов: {}',
  'Add the best {}': 'Добавить лучшие: {}',
  'Let me choose': 'Выбрать самому',
  '{} of {} selected': 'Выбрано {} из {}',
  'Select all': 'Выбрать все',
  'Deselect all': 'Снять выбор',
  'Tip: press and hold a row, then drag to select many.': 'Совет: нажмите и удерживайте строку, затем проведите, чтобы выбрать несколько.',
  'Add {}': 'Добавить {}',
  'Appearance': 'Оформление',
  'Auto': 'Авто',
  'Latte': 'Latte',
  'Mocha': 'Mocha',
  'Language': 'Язык',
  'System default': 'Как в системе',
  'Network': 'Сеть',
  'Proxy port': 'Порт прокси',
  'SOCKS5 proxy, also available while TUN is on': 'Прокси SOCKS5, доступен и при включённом TUN',
  'Allow LAN connections': 'Разрешить подключения из LAN',
  'Let other devices use the proxy': 'Разрешить другим устройствам использовать прокси',
  'Startup': 'Запуск',
  'Connect on launch': 'Подключаться при запуске',
  'Start the tunnel when Pray opens': 'Запускать туннель при открытии Pray',
  'Launch at login': 'Запускать при входе',
  'Start Pray with your session': 'Запускать Pray вместе с сессией',
  'Core': 'Ядро',
  'Geo data': 'Гео-данные',
  'Download the latest geoip and geosite': 'Скачать последние geoip и geosite',
  'Last updated {}': 'Обновлено {}',
  'Geo data updated. Reconnect to use it.': 'Гео-данные обновлены. Переподключитесь, чтобы использовать их.',
  'Enter a port from {} to {}': 'Введите порт от {} до {}',
  'Version {}': 'Версия {}',
  'Made with love by {}': 'Сделано с любовью: {}',
  'Links': 'Ссылки',
  'Built with': 'Создано с помощью',
  'The toolkit behind the interface': 'Инструментарий интерфейса',
  'The language it is written in': 'Язык, на котором написано приложение',
  'The engine behind every connection': 'Движок каждого соединения',
  'The Mocha and Latte palettes': 'Палитры Mocha и Latte',
  'The typeface, under the SIL Open Font License': 'Шрифт под лицензией SIL Open Font License',
  'Copy link': 'Копировать ссылку',
  'Couldn\'t open {}': 'Не удалось открыть {}',
  'Couldn\'t download: {}': 'Не удалось скачать: {}',
  'What does this do?': 'Что это делает?',
  'Got it': 'Понятно',
  'Show': 'Показать',
  'Failed: {}.': 'Не удалось: {}.',
  'HTTP {}': 'HTTP {}',
  'Delete {} servers?': 'Удалить серверы ({})?',
  'Donate': 'Поддержать',
  'YouTube ads': 'Реклама YouTube',
  'Blocks YouTube and Google ad requests. Ads served inside the video itself still show.': 'Блокирует рекламные запросы YouTube и Google. Реклама внутри самого видео всё равно показывается.',
  'Nothing is blocked.': 'Ничего не блокируется.',
  'Blocks the well-known ad networks and trackers.': 'Блокирует известные рекламные сети и трекеры.',
  'Standard plus extra ads, trackers and analytics. A few apps may break.': 'Стандартный плюс дополнительная реклама, трекеры и аналитика. Некоторые приложения могут сломаться.',
  'Renew WARP account': 'Обновить аккаунт WARP',
  'Create a new free account. Use this if WARP stops working.': 'Создать новый бесплатный аккаунт. Используйте, если WARP перестал работать.',
  'YouTube ads: blocks the ad servers YouTube and Google use for banner, display and some video ad requests. Most video ads come from the same servers as the video itself, so a few will remain. For complete YouTube ad blocking use an ad-free client.': 'Реклама YouTube: блокирует рекламные серверы, которые YouTube и Google используют для баннеров, медийной и части видеорекламы. Большая часть видеорекламы идёт с тех же серверов, что и само видео, поэтому часть рекламы останется. Для полной блокировки используйте клиент без рекламы.',
  'Could not start the administrator helper (code {}).': 'Не удалось запустить помощник администратора (код {}).',
  'Latin and Cyrillic text, under the SIL Open Font License': 'Латиница и кириллица, лицензия SIL Open Font License',
  'Persian text, under the SIL Open Font License': 'Персидский текст, лицензия SIL Open Font License',
  'Chinese text, under the SIL Open Font License': 'Китайский текст, лицензия SIL Open Font License',
  'Japanese text, under the SIL Open Font License': 'Японский текст, лицензия SIL Open Font License',
  'DNS server': 'DNS-сервер',
  'Encrypted DNS': 'Зашифрованный DNS',
  'Send lookups over HTTPS so nobody on the network can read them': 'Отправлять запросы по HTTPS, чтобы никто в сети не мог их прочитать',
  'Fake DNS': 'Fake DNS',
  'Answer lookups inside the tunnel with placeholder addresses. TUN mode only': 'Отвечать на запросы внутри туннеля подменными адресами. Только режим TUN',
  'DNS leak test': 'Тест утечки DNS',
  'See which servers answer your DNS lookups': 'Посмотрите, какие серверы отвечают на ваши DNS-запросы',
  'Custom': 'Свой',
  'Enter at least one DNS server': 'Укажите хотя бы один DNS-сервер',
  'DNS server address': 'Адрес DNS-сервера',
  'An IP like 9.9.9.9 or an https:// DoH address, separated by commas': 'IP вроде 9.9.9.9 или адрес DoH с https://, через запятую',
  'Testing…': 'Проверка…',
  'The test failed. Check your connection.': 'Тест не удался. Проверьте подключение.',
  'Your IP': 'Ваш IP',
  'No DNS servers were reported.': 'DNS-серверы не обнаружены.',
  'DNS servers that answered': 'DNS-серверы, которые ответили',
  'Run again': 'Запустить снова',
  'Update available': 'Доступно обновление',
  'Version {} is available. You have {}.': 'Вышла версия {}. У вас {}.',
  'Later': 'Позже',
  'Download': 'Скачать',
  'How it works: before connecting to a site, an app asks a DNS server for its address. Whoever answers can see every site you visit, and on some networks can fake the answer.': 'Как это работает: прежде чем подключиться к сайту, приложение спрашивает его адрес у DNS-сервера. Тот, кто отвечает, видит все сайты, которые вы открываете, а в некоторых сетях может подделать ответ.',
  'DNS server: who answers those lookups. System default uses your device\'s own DNS, which is usually your internet provider. Cloudflare, Google and Quad9 are public servers. Custom lets you enter your own.': 'DNS-сервер: кто отвечает на эти запросы. «Как в системе» использует DNS самого устройства, обычно это ваш интернет-провайдер. Cloudflare, Google и Quad9 — публичные серверы. В режиме «Свой» можно указать собственный.',
  'Encrypted DNS: sends the lookups over HTTPS, so the network between you and the server cannot read or change them.': 'Зашифрованный DNS: отправляет запросы по HTTPS, поэтому сеть между вами и сервером не может ни прочитать, ни изменить их.',
  'Fake DNS: in TUN mode, answers lookups right inside the tunnel with placeholder addresses and swaps the real site name back in when the app connects. It can be faster and avoids DNS leaks, but a few apps may break.': 'Fake DNS: в режиме TUN отвечает на запросы прямо внутри туннеля подменными адресами и возвращает настоящее имя сайта, когда приложение подключается. Это может быть быстрее и исключает утечки DNS, но некоторые приложения могут перестать работать.',
  'DNS leak test: checks which servers really answer your lookups. If you see your own provider while connected, DNS is leaking.': 'Тест утечки DNS: проверяет, какие серверы на самом деле отвечают на ваши запросы. Если при подключении вы видите своего провайдера, DNS утекает.',
};
